.TH "core_template" 3 "Fri Dec 14 2018" "IMAC3_CG_CPP_Game_Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
core_template \- The generic template types used as the basis for the core types\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
The generic template types used as the basis for the core types\&. 

These types are all templates used to define the actual \fBTypes\fP\&. These templetes are implementation details of GLM types and should not be used explicitly\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for IMAC3_CG_CPP_Game_Project from the source code\&.
