.TH "core_func_geometric" 3 "Tue Dec 18 2018" "IMAC run" \" -*- nroff -*-
.ad l
.nh
.SH NAME
core_func_geometric
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL genType::value_type \fBglm::length\fP (genType const &x)"
.br
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL genType::value_type \fBglm::distance\fP (genType const &p0, genType const &p1)"
.br
.ti -1c
.RI "template<typename T , precision P, template< typename, precision > class vecType> GLM_FUNC_DECL T \fBglm::dot\fP (vecType< T, P > const &x, vecType< T, P > const &y)"
.br
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL genType \fBglm::dot\fP (genType const &x, genType const &y)"
.br
.ti -1c
.RI "template<typename T , precision P> GLM_FUNC_DECL \fBdetail::tvec3\fP< T, P > \fBglm::cross\fP (\fBdetail::tvec3\fP< T, P > const &x, \fBdetail::tvec3\fP< T, P > const &y)"
.br
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL genType \fBglm::normalize\fP (genType const &x)"
.br
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL genType \fBglm::faceforward\fP (genType const &N, genType const &I, genType const &Nref)"
.br
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL genType \fBglm::reflect\fP (genType const &I, genType const &N)"
.br
.ti -1c
.RI "template<typename T , precision P, template< typename, precision > class vecType> GLM_FUNC_DECL vecType< T, P > \fBglm::refract\fP (vecType< T, P > const &I, vecType< T, P > const &N, T const &eta)"
.br
.in -1c
.SH "Detailed Description"
.PP 
These operate on vectors as vectors, not component-wise\&. 
.SH "Function Documentation"
.PP 
.SS "template<typename T , precision P> GLM_FUNC_DECL \fBdetail::tvec3\fP<T, P> glm::cross (\fBdetail::tvec3\fP< T, P > const & x, \fBdetail::tvec3\fP< T, P > const & y)"
Returns the cross product of x and y\&.
.PP
\fBTemplate Parameters:\fP
.RS 4
\fIvalType\fP Floating-point scalar types\&.
.RE
.PP
\fBSee also:\fP
.RS 4
\fCGLSL cross man page\fP 
.PP
\fCGLSL 4\&.20\&.8 specification, section 8\&.5 Geometric Functions\fP 
.RE
.PP

.SS "template<typename genType > GLM_FUNC_DECL genType::value_type glm::distance (genType const & p0, genType const & p1)"
Returns the distance betwwen p0 and p1, i\&.e\&., length(p0 - p1)\&.
.PP
\fBTemplate Parameters:\fP
.RS 4
\fIgenType\fP Floating-point vector types\&.
.RE
.PP
\fBSee also:\fP
.RS 4
\fCGLSL distance man page\fP 
.PP
\fCGLSL 4\&.20\&.8 specification, section 8\&.5 Geometric Functions\fP 
.RE
.PP

.SS "template<typename T , precision P, template< typename, precision > class vecType> GLM_FUNC_DECL T glm::dot (vecType< T, P > const & x, vecType< T, P > const & y)"
Returns the dot product of x and y, i\&.e\&., result = x * y\&.
.PP
\fBTemplate Parameters:\fP
.RS 4
\fIgenType\fP Floating-point vector types\&.
.RE
.PP
\fBSee also:\fP
.RS 4
\fCGLSL dot man page\fP 
.PP
\fCGLSL 4\&.20\&.8 specification, section 8\&.5 Geometric Functions\fP 
.RE
.PP

.SS "template<typename genType > GLM_FUNC_DECL genType glm::dot (genType const & x, genType const & y)"
Returns the dot product of x and y, i\&.e\&., result = x * y\&.
.PP
\fBTemplate Parameters:\fP
.RS 4
\fIgenType\fP Floating-point vector types\&.
.RE
.PP
\fBSee also:\fP
.RS 4
\fCGLSL dot man page\fP 
.PP
\fCGLSL 4\&.20\&.8 specification, section 8\&.5 Geometric Functions\fP 
.RE
.PP

.SS "template<typename genType > GLM_FUNC_DECL genType glm::faceforward (genType const & N, genType const & I, genType const & Nref)"
If dot(Nref, I) < 0\&.0, return N, otherwise, return -N\&.
.PP
\fBTemplate Parameters:\fP
.RS 4
\fIgenType\fP Floating-point vector types\&.
.RE
.PP
\fBSee also:\fP
.RS 4
\fCGLSL faceforward man page\fP 
.PP
\fCGLSL 4\&.20\&.8 specification, section 8\&.5 Geometric Functions\fP 
.RE
.PP

.SS "template<typename genType > GLM_FUNC_DECL genType::value_type glm::length (genType const & x)"
Returns the length of x, i\&.e\&., sqrt(x * x)\&.
.PP
\fBTemplate Parameters:\fP
.RS 4
\fIgenType\fP Floating-point vector types\&.
.RE
.PP
\fBSee also:\fP
.RS 4
\fCGLSL length man page\fP 
.PP
\fCGLSL 4\&.20\&.8 specification, section 8\&.5 Geometric Functions\fP 
.RE
.PP

.SS "template<typename genType > GLM_FUNC_DECL genType glm::normalize (genType const & x)"
Returns a vector in the same direction as x but with length of 1\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL normalize man page\fP 
.PP
\fCGLSL 4\&.20\&.8 specification, section 8\&.5 Geometric Functions\fP 
.RE
.PP

.SS "template<typename genType > GLM_FUNC_DECL genType glm::reflect (genType const & I, genType const & N)"
For the incident vector I and surface orientation N, returns the reflection direction : result = I - 2\&.0 * dot(N, I) * N\&.
.PP
\fBTemplate Parameters:\fP
.RS 4
\fIgenType\fP Floating-point vector types\&.
.RE
.PP
\fBSee also:\fP
.RS 4
\fCGLSL reflect man page\fP 
.PP
\fCGLSL 4\&.20\&.8 specification, section 8\&.5 Geometric Functions\fP 
.RE
.PP

.SS "template<typename T , precision P, template< typename, precision > class vecType> GLM_FUNC_DECL vecType<T, P> glm::refract (vecType< T, P > const & I, vecType< T, P > const & N, T const & eta)"
For the incident vector I and surface normal N, and the ratio of indices of refraction eta, return the refraction vector\&.
.PP
\fBTemplate Parameters:\fP
.RS 4
\fIgenType\fP Floating-point vector types\&.
.RE
.PP
\fBSee also:\fP
.RS 4
\fCGLSL refract man page\fP 
.PP
\fCGLSL 4\&.20\&.8 specification, section 8\&.5 Geometric Functions\fP 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for IMAC run from the source code\&.
