.TH "core" 3 "Fri Dec 14 2018" "IMAC3_CG_CPP_Game_Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
core \- The core of GLM, which implements exactly and only the GLSL specification to the degree possible\&.  

.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBCommon functions\fP"
.br
.ti -1c
.RI "\fBExponential functions\fP"
.br
.ti -1c
.RI "\fBGeometric functions\fP"
.br
.ti -1c
.RI "\fBInteger functions\fP"
.br
.ti -1c
.RI "\fBMatrix functions\fP"
.br
.ti -1c
.RI "\fBNoise functions\fP"
.br
.ti -1c
.RI "\fBFloating\-Point Pack and Unpack Functions\fP"
.br
.ti -1c
.RI "\fBAngle and Trigonometry Functions\fP"
.br
.ti -1c
.RI "\fBVector Relational Functions\fP"
.br
.ti -1c
.RI "\fBTypes\fP"
.br
.RI "The standard types defined by the specification\&. "
.ti -1c
.RI "\fBPrecision types\fP"
.br
.RI "Non-GLSL types that are used to define precision-based types\&. "
.ti -1c
.RI "\fBTemplate types\fP"
.br
.RI "The generic template types used as the basis for the core types\&. "
.in -1c
.SH "Detailed Description"
.PP 
The core of GLM, which implements exactly and only the GLSL specification to the degree possible\&. 

The GLM core consists of \fBC++ types that mirror GLSL types\fP and C++ functions that mirror the GLSL functions\&. It also includes \fBa set of precision-based types\fP that can be used in the appropriate functions\&. The C++ types are all based on a basic set of \fBtemplate types\fP\&.
.PP
The best documentation for GLM Core is the current GLSL specification, \fCversion 4\&.2 (pdf file)\fP\&. There are a few \fBdifferences\fP between GLM core and GLSL\&.
.PP
GLM core functionnalities require <\fBglm/glm\&.hpp\fP> to be included to be used\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for IMAC3_CG_CPP_Game_Project from the source code\&.
