.TH "includes/GraphicsEngine/Events/EventManager.hpp" 3 "Tue Dec 18 2018" "IMAC run" \" -*- nroff -*-
.ad l
.nh
.SH NAME
includes/GraphicsEngine/Events/EventManager.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <vector>\fP
.br
\fC#include <memory>\fP
.br
\fC#include <set>\fP
.br
\fC#include 'Frameworks\&.hpp'\fP
.br
\fC#include 'EventObservers\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBGraphicsEngine::EventManager\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBGraphicsEngine\fP"
.br
.RI "gestion des évenements "
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBVersion:\fP
.RS 4
0\&.2 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for IMAC run from the source code\&.
