.TH "GameController" 3 "Tue Dec 18 2018" "IMAC run" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GameController
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBQuitEventObserver\fP, \fBKeyboardEventObserver\fP, and \fBMouseEventObserver\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBsetup\fP ()"
.br
.ti -1c
.RI "bool \fBloop\fP ()"
.br
.ti -1c
.RI "void \fBquitEventHandler\fP () override"
.br
.ti -1c
.RI "void \fBkeyDownHandler\fP (unsigned char keycode) override"
.br
.ti -1c
.RI "void \fBkeyRealeaseHandler\fP (unsigned char keycode) override"
.br
.ti -1c
.RI "void \fBmouseMoveHandler\fP (float relativeXMovement, float relativeYMovement) override"
.br
.ti -1c
.RI "void \fBmouseWheelHandler\fP (float deltaX, float deltaY) override"
.br
.ti -1c
.RI "void \fBmouseReleaseHandler\fP (unsigned char button) override"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBGameController\fP * \fBinstance\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for IMAC run from the source code\&.
