.TH "glm::detail::compute_sqrt< detail::tvec3, T, P >" 3 "Fri Dec 14 2018" "IMAC3_CG_CPP_Game_Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
glm::detail::compute_sqrt< detail::tvec3, T, P >
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static GLM_FUNC_QUALIFIER \fBdetail::tvec3\fP< T, P > \fBcall\fP (\fBdetail::tvec3\fP< T, P > const &x)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for IMAC3_CG_CPP_Game_Project from the source code\&.
