.TH "glm::io::format_punct< CTy >" 3 "Fri Dec 14 2018" "IMAC3_CG_CPP_Game_Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
glm::io::format_punct< CTy >
.SH SYNOPSIS
.br
.PP
.PP
Inherits facet\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBformat_punct\fP (size_t a=0)"
.br
.ti -1c
.RI "\fBformat_punct\fP (\fBformat_punct\fP const &)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBformatted\fP"
.br
.ti -1c
.RI "unsigned \fBprecision\fP"
.br
.ti -1c
.RI "unsigned \fBwidth\fP"
.br
.ti -1c
.RI "char_type \fBseparator\fP"
.br
.ti -1c
.RI "char_type \fBdelim_left\fP"
.br
.ti -1c
.RI "char_type \fBdelim_right\fP"
.br
.ti -1c
.RI "char_type \fBspace\fP"
.br
.ti -1c
.RI "char_type \fBnewline\fP"
.br
.ti -1c
.RI "order_type \fBorder\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static std::locale::id \fBid\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for IMAC3_CG_CPP_Game_Project from the source code\&.
