.TH "glm::detail::compute_transpose< detail::tmat4x3, T, P >" 3 "Tue Dec 18 2018" "IMAC run" \" -*- nroff -*-
.ad l
.nh
.SH NAME
glm::detail::compute_transpose< detail::tmat4x3, T, P >
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static GLM_FUNC_QUALIFIER \fBdetail::tmat3x4\fP< T, P > \fBcall\fP (\fBdetail::tmat4x3\fP< T, P > const &m)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for IMAC run from the source code\&.
