.TH "glm::detail::higherMultiple< Signed >" 3 "Fri Dec 14 2018" "IMAC3_CG_CPP_Game_Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
glm::detail::higherMultiple< Signed >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename genType > GLM_FUNC_QUALIFIER \fBgenType\fP \fBoperator()\fP (\fBgenType\fP const &Source, \fBgenType\fP const &Multiple)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for IMAC3_CG_CPP_Game_Project from the source code\&.
