.TH "glm::detail::_swizzle_base0< T, N >" 3 "Tue Dec 18 2018" "IMAC run" \" -*- nroff -*-
.ad l
.nh
.SH NAME
glm::detail::_swizzle_base0< T, N >
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBglm::detail::_swizzle_base1< T, P, V, E0, E1, E2, E3, N >\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef T \fBvalue_type\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "GLM_FUNC_QUALIFIER value_type & \fBelem\fP (size_t i)"
.br
.ti -1c
.RI "GLM_FUNC_QUALIFIER const value_type & \fBelem\fP (size_t i) const"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "char \fB_buffer\fP [1]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for IMAC run from the source code\&.
