.TH "glm::detail::i10i10i10i2" 3 "Tue Dec 18 2018" "IMAC run" \" -*- nroff -*-
.ad l
.nh
.SH NAME
glm::detail::i10i10i10i2
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   int \fBx\fP: 10"
.br
.ti -1c
.RI "   int \fBy\fP: 10"
.br
.ti -1c
.RI "   int \fBz\fP: 10"
.br
.ti -1c
.RI "   int \fBw\fP: 2"
.br
.ti -1c
.RI "} \fBdata\fP"
.br
.ti -1c
.RI "\fBuint32\fP \fBpack\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for IMAC run from the source code\&.
