.TH "glm::detail::compute_outerProduct< detail::tvec3, detail::tvec3, T, P >" 3 "Tue Dec 18 2018" "IMAC run" \" -*- nroff -*-
.ad l
.nh
.SH NAME
glm::detail::compute_outerProduct< detail::tvec3, detail::tvec3, T, P >
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static GLM_FUNC_QUALIFIER \fBdetail::outerProduct_trait\fP< T, P, \fBdetail::tvec3\fP, \fBdetail::tvec3\fP >::type \fBcall\fP (\fBdetail::tvec3\fP< T, P > const &c, \fBdetail::tvec3\fP< T, P > const &r)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for IMAC run from the source code\&.
