.TH "glm::detail::genType< VALTYPE, TYPE >" 3 "Fri Dec 14 2018" "IMAC3_CG_CPP_Game_Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
glm::detail::genType< VALTYPE, TYPE >
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBctor\fP { \fBnull\fP }"
.br
.ti -1c
.RI "typedef VALTYPE \fBvalue_type\fP"
.br
.ti -1c
.RI "typedef VALTYPE & \fBvalue_reference\fP"
.br
.ti -1c
.RI "typedef VALTYPE * \fBvalue_pointer\fP"
.br
.ti -1c
.RI "typedef VALTYPE const  * \fBvalue_const_pointer\fP"
.br
.ti -1c
.RI "typedef TYPE< bool > \fBbool_type\fP"
.br
.ti -1c
.RI "typedef sizeType \fBsize_type\fP"
.br
.ti -1c
.RI "typedef TYPE< VALTYPE > \fBtype\fP"
.br
.ti -1c
.RI "typedef TYPE< VALTYPE > * \fBpointer\fP"
.br
.ti -1c
.RI "typedef TYPE< VALTYPE > const  * \fBconst_pointer\fP"
.br
.ti -1c
.RI "typedef TYPE< VALTYPE > const  *const \fBconst_pointer_const\fP"
.br
.ti -1c
.RI "typedef TYPE< VALTYPE > *const \fBpointer_const\fP"
.br
.ti -1c
.RI "typedef TYPE< VALTYPE > & \fBreference\fP"
.br
.ti -1c
.RI "typedef TYPE< VALTYPE > const  & \fBconst_reference\fP"
.br
.ti -1c
.RI "typedef TYPE< VALTYPE > const  & \fBparam_type\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "value_const_pointer \fBvalue_address\fP () const"
.br
.ti -1c
.RI "value_pointer \fBvalue_address\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBis_vector\fP ()"
.br
.ti -1c
.RI "static bool \fBis_matrix\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for IMAC3_CG_CPP_Game_Project from the source code\&.
