.TH "glm::detail::compute_mix_vector< T, U, P, vecType >" 3 "Tue Dec 18 2018" "IMAC run" \" -*- nroff -*-
.ad l
.nh
.SH NAME
glm::detail::compute_mix_vector< T, U, P, vecType >
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static GLM_FUNC_QUALIFIER vecType< T, P > \fBcall\fP (vecType< T, P > const &x, vecType< T, P > const &y, vecType< U, P > const &a)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for IMAC run from the source code\&.
