.TH "glm::detail::ieee754_QNAN::i" 3 "Fri Dec 14 2018" "IMAC3_CG_CPP_Game_Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
glm::detail::ieee754_QNAN::i
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const unsigned int \fBmantissa\fP:23"
.br
.ti -1c
.RI "const unsigned int \fBexp\fP:8"
.br
.ti -1c
.RI "const unsigned int \fBsign\fP:1"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for IMAC3_CG_CPP_Game_Project from the source code\&.
