.TH "glm::detail::compute_areCollinear< T, P, tvec3 >" 3 "Fri Dec 14 2018" "IMAC3_CG_CPP_Game_Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
glm::detail::compute_areCollinear< T, P, tvec3 >
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static GLM_FUNC_QUALIFIER bool \fBcall\fP (\fBdetail::tvec3\fP< T, P > const &v0, \fBdetail::tvec3\fP< T, P > const &v1, T const &\fBepsilon\fP)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for IMAC3_CG_CPP_Game_Project from the source code\&.
