.TH "glm::detail::tmat2x2< T, P >" 3 "Tue Dec 18 2018" "IMAC run" \" -*- nroff -*-
.ad l
.nh
.SH NAME
glm::detail::tmat2x2< T, P >
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBctor\fP { \fB_null\fP }"
.br
.ti -1c
.RI "typedef T \fBvalue_type\fP"
.br
.ti -1c
.RI "typedef std::size_t \fBsize_type\fP"
.br
.ti -1c
.RI "typedef \fBtvec2\fP< T, P > \fBcol_type\fP"
.br
.ti -1c
.RI "typedef \fBtvec2\fP< T, P > \fBrow_type\fP"
.br
.ti -1c
.RI "typedef \fBtmat2x2\fP< T, P > \fBtype\fP"
.br
.ti -1c
.RI "typedef \fBtmat2x2\fP< T, P > \fBtranspose_type\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "GLM_FUNC_DECL GLM_CONSTEXPR length_t \fBlength\fP () const"
.br
.ti -1c
.RI "GLM_FUNC_DECL \fBtmat2x2\fP (\fBtmat2x2\fP< T, P > const &m)"
.br
.ti -1c
.RI "template<precision Q> GLM_FUNC_DECL \fBtmat2x2\fP (\fBtmat2x2\fP< T, Q > const &m)"
.br
.ti -1c
.RI "GLM_FUNC_DECL \fBtmat2x2\fP (ctor Null)"
.br
.ti -1c
.RI "GLM_FUNC_DECL \fBtmat2x2\fP (T const &x)"
.br
.ti -1c
.RI "GLM_FUNC_DECL \fBtmat2x2\fP (T const &x1, T const &y1, T const &x2, T const &y2)"
.br
.ti -1c
.RI "GLM_FUNC_DECL \fBtmat2x2\fP (\fBcol_type\fP const &v1, \fBcol_type\fP const &v2)"
.br
.ti -1c
.RI "template<typename U , typename V , typename M , typename N > GLM_FUNC_DECL \fBtmat2x2\fP (U const &x1, V const &y1, M const &x2, N const &y2)"
.br
.ti -1c
.RI "template<typename U , typename V > GLM_FUNC_DECL \fBtmat2x2\fP (\fBtvec2\fP< U, P > const &v1, \fBtvec2\fP< V, P > const &v2)"
.br
.ti -1c
.RI "template<typename U , precision Q> GLM_FUNC_DECL \fBtmat2x2\fP (\fBtmat2x2\fP< U, Q > const &m)"
.br
.ti -1c
.RI "GLM_FUNC_DECL \fBtmat2x2\fP (\fBtmat3x3\fP< T, P > const &x)"
.br
.ti -1c
.RI "GLM_FUNC_DECL \fBtmat2x2\fP (\fBtmat4x4\fP< T, P > const &x)"
.br
.ti -1c
.RI "GLM_FUNC_DECL \fBtmat2x2\fP (\fBtmat2x3\fP< T, P > const &x)"
.br
.ti -1c
.RI "GLM_FUNC_DECL \fBtmat2x2\fP (\fBtmat3x2\fP< T, P > const &x)"
.br
.ti -1c
.RI "GLM_FUNC_DECL \fBtmat2x2\fP (\fBtmat2x4\fP< T, P > const &x)"
.br
.ti -1c
.RI "GLM_FUNC_DECL \fBtmat2x2\fP (\fBtmat4x2\fP< T, P > const &x)"
.br
.ti -1c
.RI "GLM_FUNC_DECL \fBtmat2x2\fP (\fBtmat3x4\fP< T, P > const &x)"
.br
.ti -1c
.RI "GLM_FUNC_DECL \fBtmat2x2\fP (\fBtmat4x3\fP< T, P > const &x)"
.br
.ti -1c
.RI "GLM_FUNC_DECL \fBcol_type\fP & \fBoperator[]\fP (length_t i)"
.br
.ti -1c
.RI "GLM_FUNC_DECL \fBcol_type\fP const  & \fBoperator[]\fP (length_t i) const"
.br
.ti -1c
.RI "GLM_FUNC_DECL \fBtmat2x2\fP< T, P > & \fBoperator=\fP (\fBtmat2x2\fP< T, P > const &m)"
.br
.ti -1c
.RI "template<typename U > GLM_FUNC_DECL \fBtmat2x2\fP< T, P > & \fBoperator=\fP (\fBtmat2x2\fP< U, P > const &m)"
.br
.ti -1c
.RI "template<typename U > GLM_FUNC_DECL \fBtmat2x2\fP< T, P > & \fBoperator+=\fP (U s)"
.br
.ti -1c
.RI "template<typename U > GLM_FUNC_DECL \fBtmat2x2\fP< T, P > & \fBoperator+=\fP (\fBtmat2x2\fP< U, P > const &m)"
.br
.ti -1c
.RI "template<typename U > GLM_FUNC_DECL \fBtmat2x2\fP< T, P > & \fBoperator\-=\fP (U s)"
.br
.ti -1c
.RI "template<typename U > GLM_FUNC_DECL \fBtmat2x2\fP< T, P > & \fBoperator\-=\fP (\fBtmat2x2\fP< U, P > const &m)"
.br
.ti -1c
.RI "template<typename U > GLM_FUNC_DECL \fBtmat2x2\fP< T, P > & \fBoperator*=\fP (U s)"
.br
.ti -1c
.RI "template<typename U > GLM_FUNC_DECL \fBtmat2x2\fP< T, P > & \fBoperator*=\fP (\fBtmat2x2\fP< U, P > const &m)"
.br
.ti -1c
.RI "template<typename U > GLM_FUNC_DECL \fBtmat2x2\fP< T, P > & \fBoperator/=\fP (U s)"
.br
.ti -1c
.RI "template<typename U > GLM_FUNC_DECL \fBtmat2x2\fP< T, P > & \fBoperator/=\fP (\fBtmat2x2\fP< U, P > const &m)"
.br
.ti -1c
.RI "GLM_FUNC_DECL \fBtmat2x2\fP< T, P > & \fBoperator++\fP ()"
.br
.ti -1c
.RI "GLM_FUNC_DECL \fBtmat2x2\fP< T, P > & \fBoperator\-\-\fP ()"
.br
.ti -1c
.RI "GLM_FUNC_DECL \fBtmat2x2\fP< T, P > \fBoperator++\fP (int)"
.br
.ti -1c
.RI "GLM_FUNC_DECL \fBtmat2x2\fP< T, P > \fBoperator\-\-\fP (int)"
.br
.ti -1c
.RI "template<precision Q> GLM_FUNC_QUALIFIER \fBtmat2x2\fP (\fBtmat2x2\fP< T, Q > const &m)"
.br
.ti -1c
.RI "template<typename X1, typename Y1, typename X2 , typename Y2 > GLM_FUNC_QUALIFIER \fBtmat2x2\fP (X1 const &x1, Y1 const &y1, X2 const &x2, Y2 const &y2)"
.br
.ti -1c
.RI "template<typename V1, typename V2> GLM_FUNC_QUALIFIER \fBtmat2x2\fP (\fBtvec2\fP< V1, P > const &v1, \fBtvec2\fP< V2, P > const &v2)"
.br
.ti -1c
.RI "template<typename U, precision Q> GLM_FUNC_QUALIFIER \fBtmat2x2\fP (\fBtmat2x2\fP< U, Q > const &m)"
.br
.ti -1c
.RI "template<typename U > GLM_FUNC_QUALIFIER \fBtmat2x2\fP< T, P > & \fBoperator=\fP (\fBtmat2x2\fP< U, P > const &m)"
.br
.ti -1c
.RI "template<typename U > GLM_FUNC_QUALIFIER \fBtmat2x2\fP< T, P > & \fBoperator+=\fP (U s)"
.br
.ti -1c
.RI "template<typename U > GLM_FUNC_QUALIFIER \fBtmat2x2\fP< T, P > & \fBoperator+=\fP (\fBtmat2x2\fP< U, P > const &m)"
.br
.ti -1c
.RI "template<typename U > GLM_FUNC_QUALIFIER \fBtmat2x2\fP< T, P > & \fBoperator\-=\fP (U s)"
.br
.ti -1c
.RI "template<typename U > GLM_FUNC_QUALIFIER \fBtmat2x2\fP< T, P > & \fBoperator\-=\fP (\fBtmat2x2\fP< U, P > const &m)"
.br
.ti -1c
.RI "template<typename U > GLM_FUNC_QUALIFIER \fBtmat2x2\fP< T, P > & \fBoperator*=\fP (U s)"
.br
.ti -1c
.RI "template<typename U > GLM_FUNC_QUALIFIER \fBtmat2x2\fP< T, P > & \fBoperator*=\fP (\fBtmat2x2\fP< U, P > const &m)"
.br
.ti -1c
.RI "template<typename U > GLM_FUNC_QUALIFIER \fBtmat2x2\fP< T, P > & \fBoperator/=\fP (U s)"
.br
.ti -1c
.RI "template<typename U > GLM_FUNC_QUALIFIER \fBtmat2x2\fP< T, P > & \fBoperator/=\fP (\fBtmat2x2\fP< U, P > const &m)"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "template<typename U , precision Q> \fBtvec2\fP< U, Q > \fBoperator/\fP (\fBtmat2x2\fP< U, Q > const &m, \fBtvec2\fP< U, Q > const &v)"
.br
.ti -1c
.RI "template<typename U , precision Q> \fBtvec2\fP< U, Q > \fBoperator/\fP (\fBtvec2\fP< U, Q > const &v, \fBtmat2x2\fP< U, Q > const &m)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for IMAC run from the source code\&.
