.TH "glm::detail::tvec1< T, P >" 3 "Fri Dec 14 2018" "IMAC3_CG_CPP_Game_Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
glm::detail::tvec1< T, P >
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBctor\fP { \fB_null\fP }"
.br
.ti -1c
.RI "typedef \fBtvec1\fP< T, P > \fBtype\fP"
.br
.ti -1c
.RI "typedef \fBtvec1\fP< bool, P > \fBbool_type\fP"
.br
.ti -1c
.RI "typedef T \fBvalue_type\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "GLM_FUNC_DECL GLM_CONSTEXPR length_t \fBlength\fP () const"
.br
.ti -1c
.RI "GLM_FUNC_DECL T & \fBoperator[]\fP (length_t i)"
.br
.ti -1c
.RI "GLM_FUNC_DECL T const  & \fBoperator[]\fP (length_t i) const"
.br
.ti -1c
.RI "GLM_FUNC_DECL \fBtvec1\fP (\fBtvec1\fP< T, P > const &v)"
.br
.ti -1c
.RI "template<precision Q> GLM_FUNC_DECL \fBtvec1\fP (\fBtvec1\fP< T, Q > const &v)"
.br
.ti -1c
.RI "GLM_FUNC_DECL \fBtvec1\fP (ctor)"
.br
.ti -1c
.RI "GLM_FUNC_DECL \fBtvec1\fP (T const &s)"
.br
.ti -1c
.RI "template<typename U , precision Q> GLM_FUNC_DECL \fBtvec1\fP (\fBtvec1\fP< U, Q > const &v)"
.br
.RI "Explicit conversions (From section 5\&.4\&.1 Conversion and scalar constructors of GLSL 1\&.30\&.08 specification) "
.ti -1c
.RI "template<typename U , precision Q> GLM_FUNC_DECL \fBtvec1\fP (\fBtvec2\fP< U, Q > const &v)"
.br
.RI "Explicit conversions (From section 5\&.4\&.1 Conversion and scalar constructors of GLSL 1\&.30\&.08 specification) "
.ti -1c
.RI "template<typename U , precision Q> GLM_FUNC_DECL \fBtvec1\fP (\fBtvec3\fP< U, Q > const &v)"
.br
.RI "Explicit conversions (From section 5\&.4\&.1 Conversion and scalar constructors of GLSL 1\&.30\&.08 specification) "
.ti -1c
.RI "template<typename U , precision Q> GLM_FUNC_DECL \fBtvec1\fP (\fBtvec4\fP< U, Q > const &v)"
.br
.RI "Explicit conversions (From section 5\&.4\&.1 Conversion and scalar constructors of GLSL 1\&.30\&.08 specification) "
.ti -1c
.RI "GLM_FUNC_DECL \fBtvec1\fP< T, P > & \fBoperator=\fP (\fBtvec1\fP< T, P > const &v)"
.br
.ti -1c
.RI "template<typename U > GLM_FUNC_DECL \fBtvec1\fP< T, P > & \fBoperator=\fP (\fBtvec1\fP< U, P > const &v)"
.br
.ti -1c
.RI "template<typename U > GLM_FUNC_DECL \fBtvec1\fP< T, P > & \fBoperator+=\fP (U const &s)"
.br
.ti -1c
.RI "template<typename U > GLM_FUNC_DECL \fBtvec1\fP< T, P > & \fBoperator+=\fP (\fBtvec1\fP< U, P > const &v)"
.br
.ti -1c
.RI "template<typename U > GLM_FUNC_DECL \fBtvec1\fP< T, P > & \fBoperator\-=\fP (U const &s)"
.br
.ti -1c
.RI "template<typename U > GLM_FUNC_DECL \fBtvec1\fP< T, P > & \fBoperator\-=\fP (\fBtvec1\fP< U, P > const &v)"
.br
.ti -1c
.RI "template<typename U > GLM_FUNC_DECL \fBtvec1\fP< T, P > & \fBoperator*=\fP (U const &s)"
.br
.ti -1c
.RI "template<typename U > GLM_FUNC_DECL \fBtvec1\fP< T, P > & \fBoperator*=\fP (\fBtvec1\fP< U, P > const &v)"
.br
.ti -1c
.RI "template<typename U > GLM_FUNC_DECL \fBtvec1\fP< T, P > & \fBoperator/=\fP (U const &s)"
.br
.ti -1c
.RI "template<typename U > GLM_FUNC_DECL \fBtvec1\fP< T, P > & \fBoperator/=\fP (\fBtvec1\fP< U, P > const &v)"
.br
.ti -1c
.RI "GLM_FUNC_DECL \fBtvec1\fP< T, P > & \fBoperator++\fP ()"
.br
.ti -1c
.RI "GLM_FUNC_DECL \fBtvec1\fP< T, P > & \fBoperator\-\-\fP ()"
.br
.ti -1c
.RI "GLM_FUNC_DECL \fBtvec1\fP< T, P > \fBoperator++\fP (int)"
.br
.ti -1c
.RI "GLM_FUNC_DECL \fBtvec1\fP< T, P > \fBoperator\-\-\fP (int)"
.br
.ti -1c
.RI "template<typename U > GLM_FUNC_DECL \fBtvec1\fP< T, P > & \fBoperator%=\fP (U const &s)"
.br
.ti -1c
.RI "template<typename U > GLM_FUNC_DECL \fBtvec1\fP< T, P > & \fBoperator%=\fP (\fBtvec1\fP< U, P > const &v)"
.br
.ti -1c
.RI "template<typename U > GLM_FUNC_DECL \fBtvec1\fP< T, P > & \fBoperator &=\fP (U const &s)"
.br
.ti -1c
.RI "template<typename U > GLM_FUNC_DECL \fBtvec1\fP< T, P > & \fBoperator &=\fP (\fBtvec1\fP< U, P > const &v)"
.br
.ti -1c
.RI "template<typename U > GLM_FUNC_DECL \fBtvec1\fP< T, P > & \fBoperator|=\fP (U const &s)"
.br
.ti -1c
.RI "template<typename U > GLM_FUNC_DECL \fBtvec1\fP< T, P > & \fBoperator|=\fP (\fBtvec1\fP< U, P > const &v)"
.br
.ti -1c
.RI "template<typename U > GLM_FUNC_DECL \fBtvec1\fP< T, P > & \fBoperator^=\fP (U const &s)"
.br
.ti -1c
.RI "template<typename U > GLM_FUNC_DECL \fBtvec1\fP< T, P > & \fBoperator^=\fP (\fBtvec1\fP< U, P > const &v)"
.br
.ti -1c
.RI "template<typename U > GLM_FUNC_DECL \fBtvec1\fP< T, P > & \fBoperator<<=\fP (U const &s)"
.br
.ti -1c
.RI "template<typename U > GLM_FUNC_DECL \fBtvec1\fP< T, P > & \fBoperator<<=\fP (\fBtvec1\fP< U, P > const &v)"
.br
.ti -1c
.RI "template<typename U > GLM_FUNC_DECL \fBtvec1\fP< T, P > & \fBoperator>>=\fP (U const &s)"
.br
.ti -1c
.RI "template<typename U > GLM_FUNC_DECL \fBtvec1\fP< T, P > & \fBoperator>>=\fP (\fBtvec1\fP< U, P > const &v)"
.br
.ti -1c
.RI "template<precision Q> GLM_FUNC_QUALIFIER \fBtvec1\fP (\fBtvec1\fP< T, Q > const &v)"
.br
.ti -1c
.RI "template<typename U, precision Q> GLM_FUNC_QUALIFIER \fBtvec1\fP (\fBtvec1\fP< U, Q > const &v)"
.br
.ti -1c
.RI "template<typename U, precision Q> GLM_FUNC_QUALIFIER \fBtvec1\fP (\fBtvec2\fP< U, Q > const &v)"
.br
.ti -1c
.RI "template<typename U, precision Q> GLM_FUNC_QUALIFIER \fBtvec1\fP (\fBtvec3\fP< U, Q > const &v)"
.br
.ti -1c
.RI "template<typename U, precision Q> GLM_FUNC_QUALIFIER \fBtvec1\fP (\fBtvec4\fP< U, Q > const &v)"
.br
.ti -1c
.RI "template<typename U > GLM_FUNC_QUALIFIER \fBtvec1\fP< T, P > & \fBoperator=\fP (\fBtvec1\fP< U, P > const &v)"
.br
.ti -1c
.RI "template<typename U > GLM_FUNC_QUALIFIER \fBtvec1\fP< T, P > & \fBoperator+=\fP (U const &s)"
.br
.ti -1c
.RI "template<typename U > GLM_FUNC_QUALIFIER \fBtvec1\fP< T, P > & \fBoperator+=\fP (\fBtvec1\fP< U, P > const &v)"
.br
.ti -1c
.RI "template<typename U > GLM_FUNC_QUALIFIER \fBtvec1\fP< T, P > & \fBoperator\-=\fP (U const &s)"
.br
.ti -1c
.RI "template<typename U > GLM_FUNC_QUALIFIER \fBtvec1\fP< T, P > & \fBoperator\-=\fP (\fBtvec1\fP< U, P > const &v)"
.br
.ti -1c
.RI "template<typename U > GLM_FUNC_QUALIFIER \fBtvec1\fP< T, P > & \fBoperator*=\fP (U const &s)"
.br
.ti -1c
.RI "template<typename U > GLM_FUNC_QUALIFIER \fBtvec1\fP< T, P > & \fBoperator*=\fP (\fBtvec1\fP< U, P > const &v)"
.br
.ti -1c
.RI "template<typename U > GLM_FUNC_QUALIFIER \fBtvec1\fP< T, P > & \fBoperator/=\fP (U const &s)"
.br
.ti -1c
.RI "template<typename U > GLM_FUNC_QUALIFIER \fBtvec1\fP< T, P > & \fBoperator/=\fP (\fBtvec1\fP< U, P > const &v)"
.br
.ti -1c
.RI "template<typename U > GLM_FUNC_QUALIFIER \fBtvec1\fP< T, P > & \fBoperator%=\fP (U const &s)"
.br
.ti -1c
.RI "template<typename U > GLM_FUNC_QUALIFIER \fBtvec1\fP< T, P > & \fBoperator%=\fP (\fBtvec1\fP< U, P > const &v)"
.br
.ti -1c
.RI "template<typename U > GLM_FUNC_QUALIFIER \fBtvec1\fP< T, P > & \fBoperator|=\fP (U const &s)"
.br
.ti -1c
.RI "template<typename U > GLM_FUNC_QUALIFIER \fBtvec1\fP< T, P > & \fBoperator|=\fP (\fBtvec1\fP< U, P > const &v)"
.br
.ti -1c
.RI "template<typename U > GLM_FUNC_QUALIFIER \fBtvec1\fP< T, P > & \fBoperator^=\fP (U const &s)"
.br
.ti -1c
.RI "template<typename U > GLM_FUNC_QUALIFIER \fBtvec1\fP< T, P > & \fBoperator^=\fP (\fBtvec1\fP< U, P > const &v)"
.br
.ti -1c
.RI "template<typename U > GLM_FUNC_QUALIFIER \fBtvec1\fP< T, P > & \fBoperator<<=\fP (U const &s)"
.br
.ti -1c
.RI "template<typename U > GLM_FUNC_QUALIFIER \fBtvec1\fP< T, P > & \fBoperator<<=\fP (\fBtvec1\fP< U, P > const &v)"
.br
.ti -1c
.RI "template<typename U > GLM_FUNC_QUALIFIER \fBtvec1\fP< T, P > & \fBoperator>>=\fP (U const &s)"
.br
.ti -1c
.RI "template<typename U > GLM_FUNC_QUALIFIER \fBtvec1\fP< T, P > & \fBoperator>>=\fP (\fBtvec1\fP< U, P > const &v)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   T \fBx\fP"
.br
.ti -1c
.RI "   T \fBr\fP"
.br
.ti -1c
.RI "   T \fBs\fP"
.br
.ti -1c
.RI "}; "
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for IMAC3_CG_CPP_Game_Project from the source code\&.
