.TH "glm::detail::uif32" 3 "Fri Dec 14 2018" "IMAC3_CG_CPP_Game_Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
glm::detail::uif32
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "GLM_FUNC_QUALIFIER \fBuif32\fP (float f)"
.br
.ti -1c
.RI "GLM_FUNC_QUALIFIER \fBuif32\fP (\fBuint32\fP i)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBf\fP"
.br
.ti -1c
.RI "\fBuint32\fP \fBi\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for IMAC3_CG_CPP_Game_Project from the source code\&.
