.TH "GraphicsEngine::LocalFilePath" 3 "Fri Dec 14 2018" "IMAC3_CG_CPP_Game_Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GraphicsEngine::LocalFilePath
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CommonStructs\&.hpp>\fP
.PP
Inherits string\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLocalFilePath\fP (std::string localPath)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBsetLocation\fP (std::string executablePath)"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBLocalFilePath\fP Subclass to std::string allowing easy creation of absolutes paths relatives to the executable 

.SH "Author"
.PP 
Generated automatically by Doxygen for IMAC3_CG_CPP_Game_Project from the source code\&.
