.TH "GraphicsEngine::ImageData" 3 "Fri Dec 14 2018" "IMAC3_CG_CPP_Game_Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GraphicsEngine::ImageData
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "const GLuint \fBwidth\fP () const"
.br
.ti -1c
.RI "const GLuint \fBheight\fP () const"
.br
.ti -1c
.RI "void * \fBpixels\fP ()"
.br
.ti -1c
.RI "const void * \fBpixels\fP () const"
.br
.ti -1c
.RI "\fBImageData\fP (const char *fileName)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for IMAC3_CG_CPP_Game_Project from the source code\&.
