.TH "GraphicsEngine::Shader" 3 "Tue Dec 18 2018" "IMAC run" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GraphicsEngine::Shader
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBShader\fP (const char *path, const GLenum shaderType)"
.br
.ti -1c
.RI "GLuint \fBidentifier\fP () const"
.br
.ti -1c
.RI "GLuint & \fBidentifier\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for IMAC run from the source code\&.
