.TH "GraphicsEngine::EventManager" 3 "Fri Dec 14 2018" "IMAC3_CG_CPP_Game_Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GraphicsEngine::EventManager
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBpollEvents\fP () const"
.br
.ti -1c
.RI "void \fBsubscribe\fP (\fBQuitEventObserver\fP *quitObserver)"
.br
.ti -1c
.RI "void \fBsubscribe\fP (\fBMouseEventObserver\fP *mouseObserver)"
.br
.ti -1c
.RI "void \fBsubscribe\fP (\fBKeyboardEventObserver\fP *keyboardObserver)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBEventManager\fP * \fBinstance\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for IMAC3_CG_CPP_Game_Project from the source code\&.
