.TH "GraphicsEngine::Camera" 3 "Fri Dec 14 2018" "IMAC3_CG_CPP_Game_Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GraphicsEngine::Camera
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCamera\fP (const float fieldOfView=60\&.f, const float aspect=800\&.f/600\&.f, const float min=0\&.1f, const float max=100\&.f)"
.br
.ti -1c
.RI "void \fBmove\fP (const \fBglm::vec3\fP &to)"
.br
.ti -1c
.RI "void \fBpan\fP (const \fBglm::vec3\fP &orientation, const float angle)"
.br
.ti -1c
.RI "void \fBresetPosition\fP ()"
.br
.ti -1c
.RI "const std::shared_ptr< \fBglm::mat4\fP > \fBprojectionMatrix\fP () const"
.br
.ti -1c
.RI "const std::shared_ptr< \fBglm::mat4\fP > \fBmodelMatrix\fP () const"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for IMAC3_CG_CPP_Game_Project from the source code\&.
