.TH "GraphicsEngine" 3 "Fri Dec 14 2018" "IMAC3_CG_CPP_Game_Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GraphicsEngine
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCamera\fP"
.br
.ti -1c
.RI "class \fBController\fP"
.br
.ti -1c
.RI "class \fBEventManager\fP"
.br
.ti -1c
.RI "class \fBImageData\fP"
.br
.ti -1c
.RI "class \fBInitialisationException\fP"
.br
.ti -1c
.RI "class \fBLocalFilePath\fP"
.br
.ti -1c
.RI "class \fBMaterial\fP"
.br
.ti -1c
.RI "class \fBMesh\fP"
.br
.ti -1c
.RI "class \fBObject\fP"
.br
.ti -1c
.RI "class \fBPerspectiveShaderProgram\fP"
.br
.ti -1c
.RI "class \fBScene\fP"
.br
.ti -1c
.RI "class \fBShader\fP"
.br
.ti -1c
.RI "class \fBShaderProgram\fP"
.br
.ti -1c
.RI "class \fBTexture\fP"
.br
.ti -1c
.RI "struct \fBVertex\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
CAMERA CLASS
.PP
Facade to the glm projection matrix provides the camera's projection matrix and attributes to rotate and move the simulated camera
.PP
\fBCommonStructs\&.hpp\fP
.PP
IMAC 2 Project CG CPP
.PP
\fBEventManager\&.hpp\fP
.PP
IMAC 2 Project CG CPP EVENT MANAGER CLASS
.PP
Singleton class\&. Manages events from the SDL framework\&. Calls the right observers\&.
.PP
\fBObject\&.hpp\fP
.PP
IMAC 2 Project CG CPP GRAPHIC ENGINE CONTROLLER CLASS
.PP
Singleton, controller class of all things graphical Initialize graphics frameworks, instanciate the window, launches event fetchs, launches scenes renders\&.
.PP
\fBMaterial\&.hpp\fP
.PP
IMAC 2 Project CG CPP MATERIAL CLASS
.PP
Controls the appearance of 3D objects Manages texture and shaders\&.
.PP
PERSPECTIVE SHADER PROGRAM CLASS
.PP
Adds matrix uniforms management to the \fBShaderProgram\fP class\&.
.PP
\fBShaderProgram\&.hpp\fP
.PP
IMAC 2 Project CG CPP SHADER PROGRAM CLASS
.PP
Manages and compile vertex and fragment shaders
.PP
\fBImageData\&.hpp\fP
.PP
IMAC 2 Project CG CPP IMAGE DATA CLASS
.PP
Facade for SDL images (IMG_LOAD), with access to image data and attributes
.PP
\fBTexture\&.hpp\fP
.PP
IMAC 2 Project CG CPP TEXTURE CLASS
.PP
Creates SDL textures and loads them in a shader sampler
.PP
\fBMesh\&.hpp\fP
.PP
IMAC 2 Project CG CPP MESH CLASS
.PP
Manages and Loads in GPU, Vertices of objects\&.
.PP
\fBObject\&.hpp\fP
.PP
IMAC 2 Project CG CPP OBJECT CLASS
.PP
Join meshes and materials together\&.
.PP
Proposes transformations methods to move around objects in the scene has a draw methods that applies the material and push vertices in the pipeline\&.
.PP
\fBScene\&.hpp\fP
.PP
IMAC 2 Project CG CPP SCENE CLASS
.PP
Contains and manages the camera, objects and lights\&. Has ADD methods to populate the scene Has a DRAW method to project the scene on the camera\&.
.PP
Cameras\&.hpp
.PP
\fBCommonStructs\&.hpp\fP
.PP
\fBEventManager\&.hpp\fP
.PP
Object\&.cpp
.PP
Material\&.cpp
.PP
\fBPerspectiveShaderProgram\&.hpp\fP
.PP
ShaderProgram\&.cpp
.PP
\fBShaderProgram\&.hpp\fP
.PP
ImageData\&.cpp
.PP
Texture\&.cpp
.PP
Mesh\&.cpp
.PP
Scene\&.cpp 
.SH "Author"
.PP 
Generated automatically by Doxygen for IMAC3_CG_CPP_Game_Project from the source code\&.
