.TH "GraphicsEngine::Texture" 3 "Fri Dec 14 2018" "IMAC3_CG_CPP_Game_Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GraphicsEngine::Texture
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTexture\fP (const char *imagePath)"
.br
.ti -1c
.RI "void \fBlinkTo\fP (const \fBShaderProgram\fP &program, const char *shaderSamplerUniform='uMainTextureSampler') const"
.br
.ti -1c
.RI "const GLuint \fBidentifier\fP () const"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for IMAC3_CG_CPP_Game_Project from the source code\&.
