.TH "GraphicsEngine::Vertex" 3 "Tue Dec 18 2018" "IMAC run" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GraphicsEngine::Vertex
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CommonStructs\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBVertex\fP (\fBglm::vec3\fP position, \fBglm::vec3\fP normal, \fBglm::vec2\fP texture)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBglm::vec3\fP \fBm_position\fP"
.br
.ti -1c
.RI "\fBglm::vec3\fP \fBm_normal\fP"
.br
.ti -1c
.RI "\fBglm::vec2\fP \fBm_textureCoordinates\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
VERTEX STRUCT holds vertex data for 3D meshes\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for IMAC run from the source code\&.
