.TH "GraphicsEngine::Scene" 3 "Fri Dec 14 2018" "IMAC3_CG_CPP_Game_Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GraphicsEngine::Scene
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBadd\fP (std::shared_ptr< \fBObject\fP > &newObject)"
.br
.ti -1c
.RI "void \fBremove\fP (std::shared_ptr< \fBObject\fP > &object)"
.br
.ti -1c
.RI "void \fBrender\fP ()"
.br
.ti -1c
.RI "\fBScene\fP (\fBCamera\fP &cameraPtr)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for IMAC3_CG_CPP_Game_Project from the source code\&.
