.TH "GraphicsEngine::InitialisationException" 3 "Fri Dec 14 2018" "IMAC3_CG_CPP_Game_Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GraphicsEngine::InitialisationException
.SH SYNOPSIS
.br
.PP
.PP
Inherits exception\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "const char * \fBwhat\fP () const override  throw ()"
.br
.ti -1c
.RI "\fBInitialisationException\fP (const char *message, const char *info)"
.br
.ti -1c
.RI "\fBInitialisationException\fP (const char *message, GLuint identifier)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for IMAC3_CG_CPP_Game_Project from the source code\&.
