.TH "GraphicsEngine::Material" 3 "Tue Dec 18 2018" "IMAC run" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GraphicsEngine::Material
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMaterial\fP (\fBPerspectiveShaderProgram\fP *shader, \fBTexture\fP *texture=nullptr)"
.br
.ti -1c
.RI "\fBPerspectiveShaderProgram\fP * \fBshader\fP ()"
.br
.ti -1c
.RI "const \fBPerspectiveShaderProgram\fP * \fBshader\fP () const"
.br
.ti -1c
.RI "\fBTexture\fP * \fBtexture\fP ()"
.br
.ti -1c
.RI "const \fBTexture\fP * \fBtexture\fP () const"
.br
.ti -1c
.RI "void \fBapply\fP () const"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for IMAC run from the source code\&.
