.TH "GraphicsEngine::Controller" 3 "Fri Dec 14 2018" "IMAC3_CG_CPP_Game_Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GraphicsEngine::Controller
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBsetup\fP (const char *windowTitle='', const uint viewportWidth=800, const uint viewportHeight=600)"
.br
.ti -1c
.RI "void \fBloadScene\fP (\fBScene\fP *newScene)"
.br
.ti -1c
.RI "void \fBrender\fP ()"
.br
.ti -1c
.RI "void \fBpollEvents\fP ()"
.br
.ti -1c
.RI "void \fBprintInfos\fP ()"
.br
.ti -1c
.RI "void \fBclose\fP ()"
.br
.ti -1c
.RI "\fBScene\fP * \fBactiveScene\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBController\fP * \fBinstance\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for IMAC3_CG_CPP_Game_Project from the source code\&.
