.TH "GraphicsEngine::Mesh" 3 "Tue Dec 18 2018" "IMAC run" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GraphicsEngine::Mesh
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMesh\fP (const std::vector< \fBVertex\fP > &vertices, const GLenum drawMode=GL_TRIANGLES)"
.br
.ti -1c
.RI "const GLuint & \fBvertexArrayIdentifier\fP () const"
.br
.ti -1c
.RI "const int \fBvertexCount\fP () const"
.br
.ti -1c
.RI "const GLenum \fBmode\fP () const"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for IMAC run from the source code\&.
