.TH "GraphicsEngine::PerspectiveShaderProgram" 3 "Fri Dec 14 2018" "IMAC3_CG_CPP_Game_Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GraphicsEngine::PerspectiveShaderProgram
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBGraphicsEngine::ShaderProgram\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPerspectiveShaderProgram\fP (const char *vertexShaderSourcePath, const char *fragmentShaderSourcePath, const char *uniformMVPName='uMVPMatrix', const char *uniformMVName='uMVMatrix', const char *uniformNormName='uNormalMatrix')"
.br
.ti -1c
.RI "void \fBsetUniformMatrices\fP (const \fBglm::mat4\fP &objectModel) const"
.br
.ti -1c
.RI "void \fBsetViewMatrices\fP (const std::shared_ptr< \fBglm::mat4\fP > &projection, const std::shared_ptr< \fBglm::mat4\fP > &sceneModel)"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for IMAC3_CG_CPP_Game_Project from the source code\&.
