.TH "gtc" 3 "Tue Dec 18 2018" "IMAC run" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtc \- Functions and types that the GLSL specification doesn't define, but useful to have for a C++ program\&.  

.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBGLM_GTC_constants\fP"
.br
.RI "Provide a list of constants and precomputed useful values\&. "
.ti -1c
.RI "\fBGLM_GTC_epsilon\fP"
.br
.RI "Comparison functions for a user defined epsilon values\&. "
.ti -1c
.RI "\fBGLM_GTC_matrix_access\fP"
.br
.ti -1c
.RI "\fBGLM_GTC_matrix_integer\fP"
.br
.ti -1c
.RI "\fBGLM_GTC_matrix_inverse\fP"
.br
.ti -1c
.RI "\fBGLM_GTC_matrix_transform\fP"
.br
.RI "Defines functions that generate common transformation matrices\&. "
.ti -1c
.RI "\fBGLM_GTC_noise\fP"
.br
.ti -1c
.RI "\fBGLM_GTC_packing\fP"
.br
.RI "This extension provides a set of function to convert vertors to packed formats\&. "
.ti -1c
.RI "\fBGLM_GTC_quaternion\fP"
.br
.RI "Defines a templated quaternion type and several quaternion operations\&. "
.ti -1c
.RI "\fBGLM_GTC_random\fP"
.br
.RI "Generate random number from various distribution methods\&. "
.ti -1c
.RI "\fBGLM_GTC_reciprocal\fP"
.br
.RI "Define secant, cosecant and cotangent functions\&. "
.ti -1c
.RI "\fBGLM_GTC_type_precision\fP"
.br
.RI "Defines specific C++-based precision types\&. "
.ti -1c
.RI "\fBGLM_GTC_type_ptr\fP"
.br
.RI "Handles the interaction between pointers and vector, matrix types\&. "
.ti -1c
.RI "\fBGLM_GTC_ulp\fP"
.br
.RI "Allow the measurement of the accuracy of a function against a reference implementation\&. This extension works on floating-point data and provide results in ULP\&. <\fBglm/gtc/ulp\&.hpp\fP> need to be included to use these features\&. "
.ti -1c
.RI "\fBGLM_GTX_dual_quaternion\fP"
.br
.RI "Defines a templated dual-quaternion type and several dual-quaternion operations\&. "
.ti -1c
.RI "\fBGLM_GTX_rotate_normalized_axis\fP"
.br
.RI "Quaternions and matrices rotations around normalized axis\&. "
.in -1c
.SH "Detailed Description"
.PP 
Functions and types that the GLSL specification doesn't define, but useful to have for a C++ program\&. 

GTC extensions aim to be stable\&.
.PP
Even if it's highly unrecommended, it's possible to include all the extensions at once by including <\fBglm/ext\&.hpp\fP>\&. Otherwise, each extension needs to be included a specific file\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for IMAC run from the source code\&.
