.TH "gtc_random" 3 "Tue Dec 18 2018" "IMAC run" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtc_random \- Generate random number from various distribution methods\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL genType \fBglm::linearRand\fP (genType const &Min, genType const &Max)"
.br
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL genType \fBglm::gaussRand\fP (genType const &Mean, genType const &Deviation)"
.br
.ti -1c
.RI "template<typename T > GLM_FUNC_DECL \fBdetail::tvec2\fP< T, defaultp > \fBglm::circularRand\fP (T const &Radius)"
.br
.ti -1c
.RI "template<typename T > GLM_FUNC_DECL \fBdetail::tvec3\fP< T, defaultp > \fBglm::sphericalRand\fP (T const &Radius)"
.br
.ti -1c
.RI "template<typename T > GLM_FUNC_DECL \fBdetail::tvec2\fP< T, defaultp > \fBglm::diskRand\fP (T const &Radius)"
.br
.ti -1c
.RI "template<typename T > GLM_FUNC_DECL \fBdetail::tvec3\fP< T, defaultp > \fBglm::ballRand\fP (T const &Radius)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Generate random number from various distribution methods\&. 

<\fBglm/gtc/random\&.hpp\fP> need to be included to use these functionalities\&. 
.SH "Function Documentation"
.PP 
.SS "template<typename T > GLM_FUNC_DECL \fBdetail::tvec3\fP<T, defaultp> glm::ballRand (T const & Radius)"
Generate a random 3D vector which coordinates are regulary distributed within the volume of a ball of a given radius
.PP
\fBParameters:\fP
.RS 4
\fIRadius\fP 
.RE
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_random\fP 
.RE
.PP

.SS "template<typename T > GLM_FUNC_DECL \fBdetail::tvec2\fP<T, defaultp> glm::circularRand (T const & Radius)"
Generate a random 2D vector which coordinates are regulary distributed on a circle of a given radius
.PP
\fBParameters:\fP
.RS 4
\fIRadius\fP 
.RE
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_random\fP 
.RE
.PP

.SS "template<typename T > GLM_FUNC_DECL \fBdetail::tvec2\fP<T, defaultp> glm::diskRand (T const & Radius)"
Generate a random 2D vector which coordinates are regulary distributed within the area of a disk of a given radius
.PP
\fBParameters:\fP
.RS 4
\fIRadius\fP 
.RE
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_random\fP 
.RE
.PP

.SS "template<typename genType > GLM_FUNC_DECL genType glm::gaussRand (genType const & Mean, genType const & Deviation)"
Generate random numbers in the interval [Min, Max], according a gaussian distribution
.PP
\fBParameters:\fP
.RS 4
\fIMean\fP 
.br
\fIDeviation\fP 
.RE
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_random\fP 
.RE
.PP

.SS "template<typename genType > GLM_FUNC_DECL genType glm::linearRand (genType const & Min, genType const & Max)"
Generate random numbers in the interval [Min, Max], according a linear distribution
.PP
\fBParameters:\fP
.RS 4
\fIMin\fP 
.br
\fIMax\fP 
.RE
.PP
\fBTemplate Parameters:\fP
.RS 4
\fIgenType\fP Value type\&. Currently supported: half (not recommanded), float or double scalars and vectors\&. 
.RE
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_random\fP 
.RE
.PP

.SS "template<typename T > GLM_FUNC_DECL \fBdetail::tvec3\fP<T, defaultp> glm::sphericalRand (T const & Radius)"
Generate a random 3D vector which coordinates are regulary distributed on a sphere of a given radius
.PP
\fBParameters:\fP
.RS 4
\fIRadius\fP 
.RE
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_random\fP 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for IMAC run from the source code\&.
