.TH "gtc_quaternion" 3 "Fri Dec 14 2018" "IMAC3_CG_CPP_Game_Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtc_quaternion \- Defines a templated quaternion type and several quaternion operations\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename T , precision P> GLM_FUNC_DECL T \fBglm::length\fP (\fBdetail::tquat\fP< T, P > const &q)"
.br
.ti -1c
.RI "template<typename T , precision P> GLM_FUNC_DECL \fBdetail::tquat\fP< T, P > \fBglm::normalize\fP (\fBdetail::tquat\fP< T, P > const &q)"
.br
.ti -1c
.RI "template<typename T , precision P, template< typename, precision > class quatType> GLM_FUNC_DECL T \fBglm::dot\fP (quatType< T, P > const &x, quatType< T, P > const &y)"
.br
.ti -1c
.RI "template<typename T , precision P> GLM_FUNC_DECL \fBdetail::tquat\fP< T, P > \fBglm::mix\fP (\fBdetail::tquat\fP< T, P > const &x, \fBdetail::tquat\fP< T, P > const &y, T const &a)"
.br
.ti -1c
.RI "template<typename T , precision P> GLM_FUNC_DECL \fBdetail::tquat\fP< T, P > \fBglm::lerp\fP (\fBdetail::tquat\fP< T, P > const &x, \fBdetail::tquat\fP< T, P > const &y, T const &a)"
.br
.ti -1c
.RI "template<typename T , precision P> GLM_FUNC_DECL \fBdetail::tquat\fP< T, P > \fBglm::slerp\fP (\fBdetail::tquat\fP< T, P > const &x, \fBdetail::tquat\fP< T, P > const &y, T const &a)"
.br
.RI "Returns the slurp interpolation between two quaternions\&. "
.ti -1c
.RI "template<typename T , precision P> GLM_FUNC_DECL \fBdetail::tquat\fP< T, P > \fBglm::conjugate\fP (\fBdetail::tquat\fP< T, P > const &q)"
.br
.ti -1c
.RI "template<typename T , precision P> GLM_FUNC_DECL \fBdetail::tquat\fP< T, P > \fBglm::inverse\fP (\fBdetail::tquat\fP< T, P > const &q)"
.br
.ti -1c
.RI "template<typename T , precision P> GLM_FUNC_DECL \fBdetail::tquat\fP< T, P > \fBglm::rotate\fP (\fBdetail::tquat\fP< T, P > const &q, T const &\fBangle\fP, \fBdetail::tvec3\fP< T, P > const &\fBaxis\fP)"
.br
.ti -1c
.RI "template<typename T , precision P> GLM_FUNC_DECL \fBdetail::tvec3\fP< T, P > \fBglm::eulerAngles\fP (\fBdetail::tquat\fP< T, P > const &x)"
.br
.ti -1c
.RI "template<typename T , precision P> GLM_FUNC_DECL T \fBglm::roll\fP (\fBdetail::tquat\fP< T, P > const &x)"
.br
.ti -1c
.RI "template<typename T , precision P> GLM_FUNC_DECL T \fBglm::pitch\fP (\fBdetail::tquat\fP< T, P > const &x)"
.br
.ti -1c
.RI "template<typename T , precision P> GLM_FUNC_DECL T \fBglm::yaw\fP (\fBdetail::tquat\fP< T, P > const &x)"
.br
.ti -1c
.RI "template<typename T , precision P> GLM_FUNC_DECL \fBdetail::tmat3x3\fP< T, P > \fBglm::mat3_cast\fP (\fBdetail::tquat\fP< T, P > const &x)"
.br
.ti -1c
.RI "template<typename T , precision P> GLM_FUNC_DECL \fBdetail::tmat4x4\fP< T, P > \fBglm::mat4_cast\fP (\fBdetail::tquat\fP< T, P > const &x)"
.br
.ti -1c
.RI "template<typename T , precision P> GLM_FUNC_DECL \fBdetail::tquat\fP< T, P > \fBglm::quat_cast\fP (\fBdetail::tmat3x3\fP< T, P > const &x)"
.br
.ti -1c
.RI "template<typename T , precision P> GLM_FUNC_DECL \fBdetail::tquat\fP< T, P > \fBglm::quat_cast\fP (\fBdetail::tmat4x4\fP< T, P > const &x)"
.br
.ti -1c
.RI "template<typename T , precision P> GLM_FUNC_DECL T \fBglm::angle\fP (\fBdetail::tquat\fP< T, P > const &x)"
.br
.ti -1c
.RI "template<typename T , precision P> GLM_FUNC_DECL \fBdetail::tvec3\fP< T, P > \fBglm::axis\fP (\fBdetail::tquat\fP< T, P > const &x)"
.br
.ti -1c
.RI "template<typename T , precision P> GLM_FUNC_DECL \fBdetail::tquat\fP< T, P > \fBglm::angleAxis\fP (T const &\fBangle\fP, \fBdetail::tvec3\fP< T, P > const &\fBaxis\fP)"
.br
.ti -1c
.RI "template<typename T , precision P> GLM_FUNC_DECL \fBdetail::tvec4\fP< bool, P > \fBglm::lessThan\fP (\fBdetail::tquat\fP< T, P > const &x, \fBdetail::tquat\fP< T, P > const &y)"
.br
.ti -1c
.RI "template<typename T , precision P> GLM_FUNC_DECL \fBdetail::tvec4\fP< bool, P > \fBglm::lessThanEqual\fP (\fBdetail::tquat\fP< T, P > const &x, \fBdetail::tquat\fP< T, P > const &y)"
.br
.ti -1c
.RI "template<typename T , precision P> GLM_FUNC_DECL \fBdetail::tvec4\fP< bool, P > \fBglm::greaterThan\fP (\fBdetail::tquat\fP< T, P > const &x, \fBdetail::tquat\fP< T, P > const &y)"
.br
.ti -1c
.RI "template<typename T , precision P> GLM_FUNC_DECL \fBdetail::tvec4\fP< bool, P > \fBglm::greaterThanEqual\fP (\fBdetail::tquat\fP< T, P > const &x, \fBdetail::tquat\fP< T, P > const &y)"
.br
.ti -1c
.RI "template<typename T , precision P> GLM_FUNC_DECL \fBdetail::tvec4\fP< bool, P > \fBglm::equal\fP (\fBdetail::tquat\fP< T, P > const &x, \fBdetail::tquat\fP< T, P > const &y)"
.br
.ti -1c
.RI "template<typename T , precision P> GLM_FUNC_DECL \fBdetail::tvec4\fP< bool, P > \fBglm::notEqual\fP (\fBdetail::tquat\fP< T, P > const &x, \fBdetail::tquat\fP< T, P > const &y)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Defines a templated quaternion type and several quaternion operations\&. 

<\fBglm/gtc/quaternion\&.hpp\fP> need to be included to use these functionalities\&. 
.SH "Function Documentation"
.PP 
.SS "template<typename T , precision P> GLM_FUNC_DECL T glm::angle (\fBdetail::tquat\fP< T, P > const & x)"
Returns the quaternion rotation angle\&.
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_quaternion\fP 
.RE
.PP

.SS "template<typename T , precision P> GLM_FUNC_DECL \fBdetail::tquat\fP<T, P> glm::angleAxis (T const & angle, \fBdetail::tvec3\fP< T, P > const & axis)"
Build a quaternion from an angle and a normalized axis\&.
.PP
\fBParameters:\fP
.RS 4
\fIangle\fP Angle expressed in radians if GLM_FORCE_RADIANS is define or degrees otherwise\&. 
.br
\fIaxis\fP Axis of the quaternion, must be normalized\&.
.RE
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_quaternion\fP 
.RE
.PP

.SS "template<typename T , precision P> GLM_FUNC_DECL \fBdetail::tvec3\fP<T, P> glm::axis (\fBdetail::tquat\fP< T, P > const & x)"
Returns the q rotation axis\&.
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_quaternion\fP 
.RE
.PP

.SS "template<typename T , precision P> GLM_FUNC_DECL \fBdetail::tquat\fP<T, P> glm::conjugate (\fBdetail::tquat\fP< T, P > const & q)"
Returns the q conjugate\&.
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_quaternion\fP 
.RE
.PP

.SS "template<typename T , precision P, template< typename, precision > class quatType> GLM_FUNC_DECL T glm::dot (quatType< T, P > const & x, quatType< T, P > const & y)"
Returns dot product of q1 and q2, i\&.e\&., q1[0] * q2[0] + q1[1] * q2[1] + \&.\&.\&.
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_quaternion\fP 
.RE
.PP

.SS "template<typename T , precision P> GLM_FUNC_DECL \fBdetail::tvec4\fP<bool, P> glm::equal (\fBdetail::tquat\fP< T, P > const & x, \fBdetail::tquat\fP< T, P > const & y)"
Returns the component-wise comparison of result x == y\&.
.PP
\fBTemplate Parameters:\fP
.RS 4
\fIquatType\fP Floating-point quaternion types\&.
.RE
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_quaternion\fP 
.RE
.PP

.SS "template<typename T , precision P> GLM_FUNC_DECL \fBdetail::tvec3\fP<T, P> glm::eulerAngles (\fBdetail::tquat\fP< T, P > const & x)"
Returns euler angles, yitch as x, yaw as y, roll as z\&. The result is expressed in radians if GLM_FORCE_RADIANS is defined or degrees otherwise\&.
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_quaternion\fP 
.RE
.PP

.SS "template<typename T , precision P> GLM_FUNC_DECL \fBdetail::tvec4\fP<bool, P> glm::greaterThan (\fBdetail::tquat\fP< T, P > const & x, \fBdetail::tquat\fP< T, P > const & y)"
Returns the component-wise comparison of result x > y\&.
.PP
\fBTemplate Parameters:\fP
.RS 4
\fIquatType\fP Floating-point quaternion types\&.
.RE
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_quaternion\fP 
.RE
.PP

.SS "template<typename T , precision P> GLM_FUNC_DECL \fBdetail::tvec4\fP<bool, P> glm::greaterThanEqual (\fBdetail::tquat\fP< T, P > const & x, \fBdetail::tquat\fP< T, P > const & y)"
Returns the component-wise comparison of result x >= y\&.
.PP
\fBTemplate Parameters:\fP
.RS 4
\fIquatType\fP Floating-point quaternion types\&.
.RE
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_quaternion\fP 
.RE
.PP

.SS "template<typename T , precision P> GLM_FUNC_DECL \fBdetail::tquat\fP<T, P> glm::inverse (\fBdetail::tquat\fP< T, P > const & q)"
Returns the q inverse\&.
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_quaternion\fP 
.RE
.PP

.SS "template<typename T , precision P> GLM_FUNC_DECL T glm::length (\fBdetail::tquat\fP< T, P > const & q)"
Returns the length of the quaternion\&.
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_quaternion\fP 
.RE
.PP

.SS "template<typename T , precision P> GLM_FUNC_DECL \fBdetail::tquat\fP<T, P> glm::lerp (\fBdetail::tquat\fP< T, P > const & x, \fBdetail::tquat\fP< T, P > const & y, T const & a)"
Linear interpolation of two quaternions\&. The interpolation is oriented\&.
.PP
\fBParameters:\fP
.RS 4
\fIx\fP A quaternion 
.br
\fIy\fP A quaternion 
.br
\fIa\fP Interpolation factor\&. The interpolation is defined in the range [0, 1]\&. 
.RE
.PP
\fBTemplate Parameters:\fP
.RS 4
\fIT\fP Value type used to build the quaternion\&. Supported: half, float or double\&. 
.RE
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_quaternion\fP 
.RE
.PP

.SS "template<typename T , precision P> GLM_FUNC_DECL \fBdetail::tvec4\fP<bool, P> glm::lessThan (\fBdetail::tquat\fP< T, P > const & x, \fBdetail::tquat\fP< T, P > const & y)"
Returns the component-wise comparison result of x < y\&.
.PP
\fBTemplate Parameters:\fP
.RS 4
\fIquatType\fP Floating-point quaternion types\&.
.RE
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_quaternion\fP 
.RE
.PP

.SS "template<typename T , precision P> GLM_FUNC_DECL \fBdetail::tvec4\fP<bool, P> glm::lessThanEqual (\fBdetail::tquat\fP< T, P > const & x, \fBdetail::tquat\fP< T, P > const & y)"
Returns the component-wise comparison of result x <= y\&.
.PP
\fBTemplate Parameters:\fP
.RS 4
\fIquatType\fP Floating-point quaternion types\&.
.RE
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_quaternion\fP 
.RE
.PP

.SS "template<typename T , precision P> GLM_FUNC_DECL \fBdetail::tmat3x3\fP<T, P> glm::mat3_cast (\fBdetail::tquat\fP< T, P > const & x)"
Converts a quaternion to a 3 * 3 matrix\&.
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_quaternion\fP 
.RE
.PP

.SS "template<typename T , precision P> GLM_FUNC_DECL \fBdetail::tmat4x4\fP<T, P> glm::mat4_cast (\fBdetail::tquat\fP< T, P > const & x)"
Converts a quaternion to a 4 * 4 matrix\&.
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_quaternion\fP 
.RE
.PP

.SS "template<typename T , precision P> GLM_FUNC_DECL \fBdetail::tquat\fP<T, P> glm::mix (\fBdetail::tquat\fP< T, P > const & x, \fBdetail::tquat\fP< T, P > const & y, T const & a)"
Spherical linear interpolation of two quaternions\&. The interpolation is oriented and the rotation is performed at constant speed\&. For short path spherical linear interpolation, use the slerp function\&.
.PP
\fBParameters:\fP
.RS 4
\fIx\fP A quaternion 
.br
\fIy\fP A quaternion 
.br
\fIa\fP Interpolation factor\&. The interpolation is defined beyond the range [0, 1]\&. 
.RE
.PP
\fBTemplate Parameters:\fP
.RS 4
\fIT\fP Value type used to build the quaternion\&. Supported: half, float or double\&. 
.RE
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_quaternion\fP 
.PP
- \fBslerp(detail::tquat<T, P> const & x, detail::tquat<T, P> const & y, T const & a)\fP 
.RE
.PP

.SS "template<typename T , precision P> GLM_FUNC_DECL \fBdetail::tquat\fP<T, P> glm::normalize (\fBdetail::tquat\fP< T, P > const & q)"
Returns the normalized quaternion\&.
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_quaternion\fP 
.RE
.PP

.SS "template<typename T , precision P> GLM_FUNC_DECL \fBdetail::tvec4\fP<bool, P> glm::notEqual (\fBdetail::tquat\fP< T, P > const & x, \fBdetail::tquat\fP< T, P > const & y)"
Returns the component-wise comparison of result x != y\&.
.PP
\fBTemplate Parameters:\fP
.RS 4
\fIquatType\fP Floating-point quaternion types\&.
.RE
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_quaternion\fP 
.RE
.PP

.SS "template<typename T , precision P> GLM_FUNC_DECL T glm::pitch (\fBdetail::tquat\fP< T, P > const & x)"
Returns pitch value of euler angles expressed in radians if GLM_FORCE_RADIANS is defined or degrees otherwise\&.
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTX_quaternion\fP 
.RE
.PP

.SS "template<typename T , precision P> GLM_FUNC_DECL \fBdetail::tquat\fP<T, P> glm::quat_cast (\fBdetail::tmat3x3\fP< T, P > const & x)"
Converts a 3 * 3 matrix to a quaternion\&.
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_quaternion\fP 
.RE
.PP

.SS "template<typename T , precision P> GLM_FUNC_DECL \fBdetail::tquat\fP<T, P> glm::quat_cast (\fBdetail::tmat4x4\fP< T, P > const & x)"
Converts a 4 * 4 matrix to a quaternion\&.
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_quaternion\fP 
.RE
.PP

.SS "template<typename T , precision P> GLM_FUNC_DECL T glm::roll (\fBdetail::tquat\fP< T, P > const & x)"
Returns roll value of euler angles expressed in radians if GLM_FORCE_RADIANS is defined or degrees otherwise\&.
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTX_quaternion\fP 
.RE
.PP

.SS "template<typename T , precision P> GLM_FUNC_DECL \fBdetail::tquat\fP<T, P> glm::rotate (\fBdetail::tquat\fP< T, P > const & q, T const & angle, \fBdetail::tvec3\fP< T, P > const & axis)"
Rotates a quaternion from a vector of 3 components axis and an angle\&.
.PP
\fBParameters:\fP
.RS 4
\fIq\fP Source orientation 
.br
\fIangle\fP Angle expressed in radians if GLM_FORCE_RADIANS is define or degrees otherwise\&. 
.br
\fIaxis\fP Axis of the rotation
.RE
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_quaternion\fP 
.RE
.PP

.SS "template<typename T , precision P> GLM_FUNC_DECL \fBdetail::tquat\fP<T, P> glm::slerp (\fBdetail::tquat\fP< T, P > const & x, \fBdetail::tquat\fP< T, P > const & y, T const & a)"

.PP
Returns the slurp interpolation between two quaternions\&. Spherical linear interpolation of two quaternions\&. The interpolation always take the short path and the rotation is performed at constant speed\&.
.PP
\fBParameters:\fP
.RS 4
\fIx\fP A quaternion 
.br
\fIy\fP A quaternion 
.br
\fIa\fP Interpolation factor\&. The interpolation is defined beyond the range [0, 1]\&. 
.RE
.PP
\fBTemplate Parameters:\fP
.RS 4
\fIT\fP Value type used to build the quaternion\&. Supported: half, float or double\&. 
.RE
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_quaternion\fP 
.RE
.PP

.SS "template<typename T , precision P> GLM_FUNC_DECL T glm::yaw (\fBdetail::tquat\fP< T, P > const & x)"
Returns yaw value of euler angles expressed in radians if GLM_FORCE_RADIANS is defined or degrees otherwise\&.
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTX_quaternion\fP 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for IMAC3_CG_CPP_Game_Project from the source code\&.
