.TH "gtc_matrix_integer" 3 "Tue Dec 18 2018" "IMAC run" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtc_matrix_integer
.SH SYNOPSIS
.br
.PP
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBdetail::tmat2x2\fP< int, highp > \fBglm::highp_imat2\fP"
.br
.ti -1c
.RI "typedef \fBdetail::tmat3x3\fP< int, highp > \fBglm::highp_imat3\fP"
.br
.ti -1c
.RI "typedef \fBdetail::tmat4x4\fP< int, highp > \fBglm::highp_imat4\fP"
.br
.ti -1c
.RI "typedef \fBdetail::tmat2x2\fP< int, highp > \fBglm::highp_imat2x2\fP"
.br
.ti -1c
.RI "typedef \fBdetail::tmat2x3\fP< int, highp > \fBglm::highp_imat2x3\fP"
.br
.ti -1c
.RI "typedef \fBdetail::tmat2x4\fP< int, highp > \fBglm::highp_imat2x4\fP"
.br
.ti -1c
.RI "typedef \fBdetail::tmat3x2\fP< int, highp > \fBglm::highp_imat3x2\fP"
.br
.ti -1c
.RI "typedef \fBdetail::tmat3x3\fP< int, highp > \fBglm::highp_imat3x3\fP"
.br
.ti -1c
.RI "typedef \fBdetail::tmat3x4\fP< int, highp > \fBglm::highp_imat3x4\fP"
.br
.ti -1c
.RI "typedef \fBdetail::tmat4x2\fP< int, highp > \fBglm::highp_imat4x2\fP"
.br
.ti -1c
.RI "typedef \fBdetail::tmat4x3\fP< int, highp > \fBglm::highp_imat4x3\fP"
.br
.ti -1c
.RI "typedef \fBdetail::tmat4x4\fP< int, highp > \fBglm::highp_imat4x4\fP"
.br
.ti -1c
.RI "typedef \fBdetail::tmat2x2\fP< int, mediump > \fBglm::mediump_imat2\fP"
.br
.ti -1c
.RI "typedef \fBdetail::tmat3x3\fP< int, mediump > \fBglm::mediump_imat3\fP"
.br
.ti -1c
.RI "typedef \fBdetail::tmat4x4\fP< int, mediump > \fBglm::mediump_imat4\fP"
.br
.ti -1c
.RI "typedef \fBdetail::tmat2x2\fP< int, mediump > \fBglm::mediump_imat2x2\fP"
.br
.ti -1c
.RI "typedef \fBdetail::tmat2x3\fP< int, mediump > \fBglm::mediump_imat2x3\fP"
.br
.ti -1c
.RI "typedef \fBdetail::tmat2x4\fP< int, mediump > \fBglm::mediump_imat2x4\fP"
.br
.ti -1c
.RI "typedef \fBdetail::tmat3x2\fP< int, mediump > \fBglm::mediump_imat3x2\fP"
.br
.ti -1c
.RI "typedef \fBdetail::tmat3x3\fP< int, mediump > \fBglm::mediump_imat3x3\fP"
.br
.ti -1c
.RI "typedef \fBdetail::tmat3x4\fP< int, mediump > \fBglm::mediump_imat3x4\fP"
.br
.ti -1c
.RI "typedef \fBdetail::tmat4x2\fP< int, mediump > \fBglm::mediump_imat4x2\fP"
.br
.ti -1c
.RI "typedef \fBdetail::tmat4x3\fP< int, mediump > \fBglm::mediump_imat4x3\fP"
.br
.ti -1c
.RI "typedef \fBdetail::tmat4x4\fP< int, mediump > \fBglm::mediump_imat4x4\fP"
.br
.ti -1c
.RI "typedef \fBdetail::tmat2x2\fP< int, lowp > \fBglm::lowp_imat2\fP"
.br
.ti -1c
.RI "typedef \fBdetail::tmat3x3\fP< int, lowp > \fBglm::lowp_imat3\fP"
.br
.ti -1c
.RI "typedef \fBdetail::tmat4x4\fP< int, lowp > \fBglm::lowp_imat4\fP"
.br
.ti -1c
.RI "typedef \fBdetail::tmat2x2\fP< int, lowp > \fBglm::lowp_imat2x2\fP"
.br
.ti -1c
.RI "typedef \fBdetail::tmat2x3\fP< int, lowp > \fBglm::lowp_imat2x3\fP"
.br
.ti -1c
.RI "typedef \fBdetail::tmat2x4\fP< int, lowp > \fBglm::lowp_imat2x4\fP"
.br
.ti -1c
.RI "typedef \fBdetail::tmat3x2\fP< int, lowp > \fBglm::lowp_imat3x2\fP"
.br
.ti -1c
.RI "typedef \fBdetail::tmat3x3\fP< int, lowp > \fBglm::lowp_imat3x3\fP"
.br
.ti -1c
.RI "typedef \fBdetail::tmat3x4\fP< int, lowp > \fBglm::lowp_imat3x4\fP"
.br
.ti -1c
.RI "typedef \fBdetail::tmat4x2\fP< int, lowp > \fBglm::lowp_imat4x2\fP"
.br
.ti -1c
.RI "typedef \fBdetail::tmat4x3\fP< int, lowp > \fBglm::lowp_imat4x3\fP"
.br
.ti -1c
.RI "typedef \fBdetail::tmat4x4\fP< int, lowp > \fBglm::lowp_imat4x4\fP"
.br
.ti -1c
.RI "typedef \fBdetail::tmat2x2\fP< \fBuint\fP, highp > \fBglm::highp_umat2\fP"
.br
.ti -1c
.RI "typedef \fBdetail::tmat3x3\fP< \fBuint\fP, highp > \fBglm::highp_umat3\fP"
.br
.ti -1c
.RI "typedef \fBdetail::tmat4x4\fP< \fBuint\fP, highp > \fBglm::highp_umat4\fP"
.br
.ti -1c
.RI "typedef \fBdetail::tmat2x2\fP< \fBuint\fP, highp > \fBglm::highp_umat2x2\fP"
.br
.ti -1c
.RI "typedef \fBdetail::tmat2x3\fP< \fBuint\fP, highp > \fBglm::highp_umat2x3\fP"
.br
.ti -1c
.RI "typedef \fBdetail::tmat2x4\fP< \fBuint\fP, highp > \fBglm::highp_umat2x4\fP"
.br
.ti -1c
.RI "typedef \fBdetail::tmat3x2\fP< \fBuint\fP, highp > \fBglm::highp_umat3x2\fP"
.br
.ti -1c
.RI "typedef \fBdetail::tmat3x3\fP< \fBuint\fP, highp > \fBglm::highp_umat3x3\fP"
.br
.ti -1c
.RI "typedef \fBdetail::tmat3x4\fP< \fBuint\fP, highp > \fBglm::highp_umat3x4\fP"
.br
.ti -1c
.RI "typedef \fBdetail::tmat4x2\fP< \fBuint\fP, highp > \fBglm::highp_umat4x2\fP"
.br
.ti -1c
.RI "typedef \fBdetail::tmat4x3\fP< \fBuint\fP, highp > \fBglm::highp_umat4x3\fP"
.br
.ti -1c
.RI "typedef \fBdetail::tmat4x4\fP< \fBuint\fP, highp > \fBglm::highp_umat4x4\fP"
.br
.ti -1c
.RI "typedef \fBdetail::tmat2x2\fP< \fBuint\fP, mediump > \fBglm::mediump_umat2\fP"
.br
.ti -1c
.RI "typedef \fBdetail::tmat3x3\fP< \fBuint\fP, mediump > \fBglm::mediump_umat3\fP"
.br
.ti -1c
.RI "typedef \fBdetail::tmat4x4\fP< \fBuint\fP, mediump > \fBglm::mediump_umat4\fP"
.br
.ti -1c
.RI "typedef \fBdetail::tmat2x2\fP< \fBuint\fP, mediump > \fBglm::mediump_umat2x2\fP"
.br
.ti -1c
.RI "typedef \fBdetail::tmat2x3\fP< \fBuint\fP, mediump > \fBglm::mediump_umat2x3\fP"
.br
.ti -1c
.RI "typedef \fBdetail::tmat2x4\fP< \fBuint\fP, mediump > \fBglm::mediump_umat2x4\fP"
.br
.ti -1c
.RI "typedef \fBdetail::tmat3x2\fP< \fBuint\fP, mediump > \fBglm::mediump_umat3x2\fP"
.br
.ti -1c
.RI "typedef \fBdetail::tmat3x3\fP< \fBuint\fP, mediump > \fBglm::mediump_umat3x3\fP"
.br
.ti -1c
.RI "typedef \fBdetail::tmat3x4\fP< \fBuint\fP, mediump > \fBglm::mediump_umat3x4\fP"
.br
.ti -1c
.RI "typedef \fBdetail::tmat4x2\fP< \fBuint\fP, mediump > \fBglm::mediump_umat4x2\fP"
.br
.ti -1c
.RI "typedef \fBdetail::tmat4x3\fP< \fBuint\fP, mediump > \fBglm::mediump_umat4x3\fP"
.br
.ti -1c
.RI "typedef \fBdetail::tmat4x4\fP< \fBuint\fP, mediump > \fBglm::mediump_umat4x4\fP"
.br
.ti -1c
.RI "typedef \fBdetail::tmat2x2\fP< \fBuint\fP, lowp > \fBglm::lowp_umat2\fP"
.br
.ti -1c
.RI "typedef \fBdetail::tmat3x3\fP< \fBuint\fP, lowp > \fBglm::lowp_umat3\fP"
.br
.ti -1c
.RI "typedef \fBdetail::tmat4x4\fP< \fBuint\fP, lowp > \fBglm::lowp_umat4\fP"
.br
.ti -1c
.RI "typedef \fBdetail::tmat2x2\fP< \fBuint\fP, lowp > \fBglm::lowp_umat2x2\fP"
.br
.ti -1c
.RI "typedef \fBdetail::tmat2x3\fP< \fBuint\fP, lowp > \fBglm::lowp_umat2x3\fP"
.br
.ti -1c
.RI "typedef \fBdetail::tmat2x4\fP< \fBuint\fP, lowp > \fBglm::lowp_umat2x4\fP"
.br
.ti -1c
.RI "typedef \fBdetail::tmat3x2\fP< \fBuint\fP, lowp > \fBglm::lowp_umat3x2\fP"
.br
.ti -1c
.RI "typedef \fBdetail::tmat3x3\fP< \fBuint\fP, lowp > \fBglm::lowp_umat3x3\fP"
.br
.ti -1c
.RI "typedef \fBdetail::tmat3x4\fP< \fBuint\fP, lowp > \fBglm::lowp_umat3x4\fP"
.br
.ti -1c
.RI "typedef \fBdetail::tmat4x2\fP< \fBuint\fP, lowp > \fBglm::lowp_umat4x2\fP"
.br
.ti -1c
.RI "typedef \fBdetail::tmat4x3\fP< \fBuint\fP, lowp > \fBglm::lowp_umat4x3\fP"
.br
.ti -1c
.RI "typedef \fBdetail::tmat4x4\fP< \fBuint\fP, lowp > \fBglm::lowp_umat4x4\fP"
.br
.ti -1c
.RI "typedef \fBmediump_imat2\fP \fBglm::imat2\fP"
.br
.ti -1c
.RI "typedef \fBmediump_imat3\fP \fBglm::imat3\fP"
.br
.ti -1c
.RI "typedef \fBmediump_imat4\fP \fBglm::imat4\fP"
.br
.ti -1c
.RI "typedef \fBmediump_imat2x2\fP \fBglm::imat2x2\fP"
.br
.ti -1c
.RI "typedef \fBmediump_imat2x3\fP \fBglm::imat2x3\fP"
.br
.ti -1c
.RI "typedef \fBmediump_imat2x4\fP \fBglm::imat2x4\fP"
.br
.ti -1c
.RI "typedef \fBmediump_imat3x2\fP \fBglm::imat3x2\fP"
.br
.ti -1c
.RI "typedef \fBmediump_imat3x3\fP \fBglm::imat3x3\fP"
.br
.ti -1c
.RI "typedef \fBmediump_imat3x4\fP \fBglm::imat3x4\fP"
.br
.ti -1c
.RI "typedef \fBmediump_imat4x2\fP \fBglm::imat4x2\fP"
.br
.ti -1c
.RI "typedef \fBmediump_imat4x3\fP \fBglm::imat4x3\fP"
.br
.ti -1c
.RI "typedef \fBmediump_imat4x4\fP \fBglm::imat4x4\fP"
.br
.ti -1c
.RI "typedef \fBmediump_umat2\fP \fBglm::umat2\fP"
.br
.ti -1c
.RI "typedef \fBmediump_umat3\fP \fBglm::umat3\fP"
.br
.ti -1c
.RI "typedef \fBmediump_umat4\fP \fBglm::umat4\fP"
.br
.ti -1c
.RI "typedef \fBmediump_umat2x2\fP \fBglm::umat2x2\fP"
.br
.ti -1c
.RI "typedef \fBmediump_umat2x3\fP \fBglm::umat2x3\fP"
.br
.ti -1c
.RI "typedef \fBmediump_umat2x4\fP \fBglm::umat2x4\fP"
.br
.ti -1c
.RI "typedef \fBmediump_umat3x2\fP \fBglm::umat3x2\fP"
.br
.ti -1c
.RI "typedef \fBmediump_umat3x3\fP \fBglm::umat3x3\fP"
.br
.ti -1c
.RI "typedef \fBmediump_umat3x4\fP \fBglm::umat3x4\fP"
.br
.ti -1c
.RI "typedef \fBmediump_umat4x2\fP \fBglm::umat4x2\fP"
.br
.ti -1c
.RI "typedef \fBmediump_umat4x3\fP \fBglm::umat4x3\fP"
.br
.ti -1c
.RI "typedef \fBmediump_umat4x4\fP \fBglm::umat4x4\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Defines a number of matrices with integer types\&. <\fBglm/gtc/matrix_integer\&.hpp\fP> need to be included to use these functionalities\&. 
.SH "Typedef Documentation"
.PP 
.SS "typedef \fBdetail::tmat2x2\fP<int, highp> \fBglm::highp_imat2\fP"
High-precision signed integer 2x2 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef \fBdetail::tmat2x2\fP<int, highp> \fBglm::highp_imat2x2\fP"
High-precision signed integer 2x2 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef \fBdetail::tmat2x3\fP<int, highp> \fBglm::highp_imat2x3\fP"
High-precision signed integer 2x3 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef \fBdetail::tmat2x4\fP<int, highp> \fBglm::highp_imat2x4\fP"
High-precision signed integer 2x4 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef \fBdetail::tmat3x3\fP<int, highp> \fBglm::highp_imat3\fP"
High-precision signed integer 3x3 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef \fBdetail::tmat3x2\fP<int, highp> \fBglm::highp_imat3x2\fP"
High-precision signed integer 3x2 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef \fBdetail::tmat3x3\fP<int, highp> \fBglm::highp_imat3x3\fP"
High-precision signed integer 3x3 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef \fBdetail::tmat3x4\fP<int, highp> \fBglm::highp_imat3x4\fP"
High-precision signed integer 3x4 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef \fBdetail::tmat4x4\fP<int, highp> \fBglm::highp_imat4\fP"
High-precision signed integer 4x4 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef \fBdetail::tmat4x2\fP<int, highp> \fBglm::highp_imat4x2\fP"
High-precision signed integer 4x2 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef \fBdetail::tmat4x3\fP<int, highp> \fBglm::highp_imat4x3\fP"
High-precision signed integer 4x3 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef \fBdetail::tmat4x4\fP<int, highp> \fBglm::highp_imat4x4\fP"
High-precision signed integer 4x4 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef \fBdetail::tmat2x2\fP<\fBuint\fP, highp> \fBglm::highp_umat2\fP"
High-precision unsigned integer 2x2 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef \fBdetail::tmat2x2\fP<\fBuint\fP, highp> \fBglm::highp_umat2x2\fP"
High-precision unsigned integer 2x2 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef \fBdetail::tmat2x3\fP<\fBuint\fP, highp> \fBglm::highp_umat2x3\fP"
High-precision unsigned integer 2x3 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef \fBdetail::tmat2x4\fP<\fBuint\fP, highp> \fBglm::highp_umat2x4\fP"
High-precision unsigned integer 2x4 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef \fBdetail::tmat3x3\fP<\fBuint\fP, highp> \fBglm::highp_umat3\fP"
High-precision unsigned integer 3x3 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef \fBdetail::tmat3x2\fP<\fBuint\fP, highp> \fBglm::highp_umat3x2\fP"
High-precision unsigned integer 3x2 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef \fBdetail::tmat3x3\fP<\fBuint\fP, highp> \fBglm::highp_umat3x3\fP"
High-precision unsigned integer 3x3 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef \fBdetail::tmat3x4\fP<\fBuint\fP, highp> \fBglm::highp_umat3x4\fP"
High-precision unsigned integer 3x4 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef \fBdetail::tmat4x4\fP<\fBuint\fP, highp> \fBglm::highp_umat4\fP"
High-precision unsigned integer 4x4 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef \fBdetail::tmat4x2\fP<\fBuint\fP, highp> \fBglm::highp_umat4x2\fP"
High-precision unsigned integer 4x2 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef \fBdetail::tmat4x3\fP<\fBuint\fP, highp> \fBglm::highp_umat4x3\fP"
High-precision unsigned integer 4x3 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef \fBdetail::tmat4x4\fP<\fBuint\fP, highp> \fBglm::highp_umat4x4\fP"
High-precision unsigned integer 4x4 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef \fBmediump_imat2\fP \fBglm::imat2\fP"
Signed integer 2x2 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef \fBmediump_imat2x2\fP \fBglm::imat2x2\fP"
Signed integer 2x2 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef \fBmediump_imat2x3\fP \fBglm::imat2x3\fP"
Signed integer 2x3 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef \fBmediump_imat2x4\fP \fBglm::imat2x4\fP"
Signed integer 2x4 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef \fBmediump_imat3\fP \fBglm::imat3\fP"
Signed integer 3x3 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef \fBmediump_imat3x2\fP \fBglm::imat3x2\fP"
Signed integer 3x2 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef \fBmediump_imat3x3\fP \fBglm::imat3x3\fP"
Signed integer 3x3 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef \fBmediump_imat3x4\fP \fBglm::imat3x4\fP"
Signed integer 3x4 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef \fBmediump_imat4\fP \fBglm::imat4\fP"
Signed integer 4x4 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef \fBmediump_imat4x2\fP \fBglm::imat4x2\fP"
Signed integer 4x2 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef \fBmediump_imat4x3\fP \fBglm::imat4x3\fP"
Signed integer 4x3 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef \fBmediump_imat4x4\fP \fBglm::imat4x4\fP"
Signed integer 4x4 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef \fBdetail::tmat2x2\fP<int, lowp> \fBglm::lowp_imat2\fP"
Low-precision signed integer 2x2 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef \fBdetail::tmat2x2\fP<int, lowp> \fBglm::lowp_imat2x2\fP"
Low-precision signed integer 2x2 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef \fBdetail::tmat2x3\fP<int, lowp> \fBglm::lowp_imat2x3\fP"
Low-precision signed integer 2x3 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef \fBdetail::tmat2x4\fP<int, lowp> \fBglm::lowp_imat2x4\fP"
Low-precision signed integer 2x4 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef \fBdetail::tmat3x3\fP<int, lowp> \fBglm::lowp_imat3\fP"
Low-precision signed integer 3x3 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef \fBdetail::tmat3x2\fP<int, lowp> \fBglm::lowp_imat3x2\fP"
Low-precision signed integer 3x2 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef \fBdetail::tmat3x3\fP<int, lowp> \fBglm::lowp_imat3x3\fP"
Low-precision signed integer 3x3 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef \fBdetail::tmat3x4\fP<int, lowp> \fBglm::lowp_imat3x4\fP"
Low-precision signed integer 3x4 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef \fBdetail::tmat4x4\fP<int, lowp> \fBglm::lowp_imat4\fP"
Low-precision signed integer 4x4 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef \fBdetail::tmat4x2\fP<int, lowp> \fBglm::lowp_imat4x2\fP"
Low-precision signed integer 4x2 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef \fBdetail::tmat4x3\fP<int, lowp> \fBglm::lowp_imat4x3\fP"
Low-precision signed integer 4x3 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef \fBdetail::tmat4x4\fP<int, lowp> \fBglm::lowp_imat4x4\fP"
Low-precision signed integer 4x4 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef \fBdetail::tmat2x2\fP<\fBuint\fP, lowp> \fBglm::lowp_umat2\fP"
Low-precision unsigned integer 2x2 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef \fBdetail::tmat2x2\fP<\fBuint\fP, lowp> \fBglm::lowp_umat2x2\fP"
Low-precision unsigned integer 2x2 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef \fBdetail::tmat2x3\fP<\fBuint\fP, lowp> \fBglm::lowp_umat2x3\fP"
Low-precision unsigned integer 2x3 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef \fBdetail::tmat2x4\fP<\fBuint\fP, lowp> \fBglm::lowp_umat2x4\fP"
Low-precision unsigned integer 2x4 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef \fBdetail::tmat3x3\fP<\fBuint\fP, lowp> \fBglm::lowp_umat3\fP"
Low-precision unsigned integer 3x3 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef \fBdetail::tmat3x2\fP<\fBuint\fP, lowp> \fBglm::lowp_umat3x2\fP"
Low-precision unsigned integer 3x2 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef \fBdetail::tmat3x3\fP<\fBuint\fP, lowp> \fBglm::lowp_umat3x3\fP"
Low-precision unsigned integer 3x3 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef \fBdetail::tmat3x4\fP<\fBuint\fP, lowp> \fBglm::lowp_umat3x4\fP"
Low-precision unsigned integer 3x4 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef \fBdetail::tmat4x4\fP<\fBuint\fP, lowp> \fBglm::lowp_umat4\fP"
Low-precision unsigned integer 4x4 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef \fBdetail::tmat4x2\fP<\fBuint\fP, lowp> \fBglm::lowp_umat4x2\fP"
Low-precision unsigned integer 4x2 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef \fBdetail::tmat4x3\fP<\fBuint\fP, lowp> \fBglm::lowp_umat4x3\fP"
Low-precision unsigned integer 4x3 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef \fBdetail::tmat4x4\fP<\fBuint\fP, lowp> \fBglm::lowp_umat4x4\fP"
Low-precision unsigned integer 4x4 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef \fBdetail::tmat2x2\fP<int, mediump> \fBglm::mediump_imat2\fP"
Medium-precision signed integer 2x2 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef \fBdetail::tmat2x2\fP<int, mediump> \fBglm::mediump_imat2x2\fP"
Medium-precision signed integer 2x2 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef \fBdetail::tmat2x3\fP<int, mediump> \fBglm::mediump_imat2x3\fP"
Medium-precision signed integer 2x3 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef \fBdetail::tmat2x4\fP<int, mediump> \fBglm::mediump_imat2x4\fP"
Medium-precision signed integer 2x4 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef \fBdetail::tmat3x3\fP<int, mediump> \fBglm::mediump_imat3\fP"
Medium-precision signed integer 3x3 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef \fBdetail::tmat3x2\fP<int, mediump> \fBglm::mediump_imat3x2\fP"
Medium-precision signed integer 3x2 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef \fBdetail::tmat3x3\fP<int, mediump> \fBglm::mediump_imat3x3\fP"
Medium-precision signed integer 3x3 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef \fBdetail::tmat3x4\fP<int, mediump> \fBglm::mediump_imat3x4\fP"
Medium-precision signed integer 3x4 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef \fBdetail::tmat4x4\fP<int, mediump> \fBglm::mediump_imat4\fP"
Medium-precision signed integer 4x4 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef \fBdetail::tmat4x2\fP<int, mediump> \fBglm::mediump_imat4x2\fP"
Medium-precision signed integer 4x2 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef \fBdetail::tmat4x3\fP<int, mediump> \fBglm::mediump_imat4x3\fP"
Medium-precision signed integer 4x3 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef \fBdetail::tmat4x4\fP<int, mediump> \fBglm::mediump_imat4x4\fP"
Medium-precision signed integer 4x4 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef \fBdetail::tmat2x2\fP<\fBuint\fP, mediump> \fBglm::mediump_umat2\fP"
Medium-precision unsigned integer 2x2 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef \fBdetail::tmat2x2\fP<\fBuint\fP, mediump> \fBglm::mediump_umat2x2\fP"
Medium-precision unsigned integer 2x2 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef \fBdetail::tmat2x3\fP<\fBuint\fP, mediump> \fBglm::mediump_umat2x3\fP"
Medium-precision unsigned integer 2x3 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef \fBdetail::tmat2x4\fP<\fBuint\fP, mediump> \fBglm::mediump_umat2x4\fP"
Medium-precision unsigned integer 2x4 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef \fBdetail::tmat3x3\fP<\fBuint\fP, mediump> \fBglm::mediump_umat3\fP"
Medium-precision unsigned integer 3x3 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef \fBdetail::tmat3x2\fP<\fBuint\fP, mediump> \fBglm::mediump_umat3x2\fP"
Medium-precision unsigned integer 3x2 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef \fBdetail::tmat3x3\fP<\fBuint\fP, mediump> \fBglm::mediump_umat3x3\fP"
Medium-precision unsigned integer 3x3 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef \fBdetail::tmat3x4\fP<\fBuint\fP, mediump> \fBglm::mediump_umat3x4\fP"
Medium-precision unsigned integer 3x4 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef \fBdetail::tmat4x4\fP<\fBuint\fP, mediump> \fBglm::mediump_umat4\fP"
Medium-precision unsigned integer 4x4 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef \fBdetail::tmat4x2\fP<\fBuint\fP, mediump> \fBglm::mediump_umat4x2\fP"
Medium-precision unsigned integer 4x2 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef \fBdetail::tmat4x3\fP<\fBuint\fP, mediump> \fBglm::mediump_umat4x3\fP"
Medium-precision unsigned integer 4x3 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef \fBdetail::tmat4x4\fP<\fBuint\fP, mediump> \fBglm::mediump_umat4x4\fP"
Medium-precision unsigned integer 4x4 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef \fBmediump_umat2\fP \fBglm::umat2\fP"
Unsigned integer 2x2 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef \fBmediump_umat2x2\fP \fBglm::umat2x2\fP"
Unsigned integer 2x2 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef \fBmediump_umat2x3\fP \fBglm::umat2x3\fP"
Unsigned integer 2x3 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef \fBmediump_umat2x4\fP \fBglm::umat2x4\fP"
Unsigned integer 2x4 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef \fBmediump_umat3\fP \fBglm::umat3\fP"
Unsigned integer 3x3 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef \fBmediump_umat3x2\fP \fBglm::umat3x2\fP"
Unsigned integer 3x2 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef \fBmediump_umat3x3\fP \fBglm::umat3x3\fP"
Unsigned integer 3x3 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef \fBmediump_umat3x4\fP \fBglm::umat3x4\fP"
Unsigned integer 3x4 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef \fBmediump_umat4\fP \fBglm::umat4\fP"
Unsigned integer 4x4 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef \fBmediump_umat4x2\fP \fBglm::umat4x2\fP"
Unsigned integer 4x2 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef \fBmediump_umat4x3\fP \fBglm::umat4x3\fP"
Unsigned integer 4x3 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef \fBmediump_umat4x4\fP \fBglm::umat4x4\fP"
Unsigned integer 4x4 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for IMAC run from the source code\&.
