.TH "gtx_normalize_dot" 3 "Tue Dec 18 2018" "IMAC run" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtx_normalize_dot \- Dot product of vectors that need to be normalize with a single square root\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL genType::value_type \fBglm::normalizeDot\fP (genType const &x, genType const &y)"
.br
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL genType::value_type \fBglm::fastNormalizeDot\fP (genType const &x, genType const &y)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Dot product of vectors that need to be normalize with a single square root\&. 

<glm/gtx/normalized_dot\&.hpp> need to be included to use these functionalities\&. 
.SH "Function Documentation"
.PP 
.SS "template<typename genType > GLM_FUNC_DECL genType::value_type glm::fastNormalizeDot (genType const & x, genType const & y)"
Normalize parameters and returns the dot product of x and y\&. Faster that dot(fastNormalize(x), fastNormalize(y))\&. From GLM_GTX_normalize_dot extension\&. 
.SS "template<typename genType > GLM_FUNC_DECL genType::value_type glm::normalizeDot (genType const & x, genType const & y)"
Normalize parameters and returns the dot product of x and y\&. It's faster that dot(normalize(x), normalize(y))\&. From GLM_GTX_normalize_dot extension\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for IMAC run from the source code\&.
