.TH "gtx_matrix_operation" 3 "Tue Dec 18 2018" "IMAC run" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtx_matrix_operation \- Build diagonal matrices from vectors\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename T , precision P> GLM_FUNC_DECL \fBdetail::tmat2x2\fP< T, P > \fBglm::diagonal2x2\fP (\fBdetail::tvec2\fP< T, P > const &v)"
.br
.ti -1c
.RI "template<typename T , precision P> GLM_FUNC_DECL \fBdetail::tmat2x3\fP< T, P > \fBglm::diagonal2x3\fP (\fBdetail::tvec2\fP< T, P > const &v)"
.br
.ti -1c
.RI "template<typename T , precision P> GLM_FUNC_DECL \fBdetail::tmat2x4\fP< T, P > \fBglm::diagonal2x4\fP (\fBdetail::tvec2\fP< T, P > const &v)"
.br
.ti -1c
.RI "template<typename T , precision P> GLM_FUNC_DECL \fBdetail::tmat3x2\fP< T, P > \fBglm::diagonal3x2\fP (\fBdetail::tvec2\fP< T, P > const &v)"
.br
.ti -1c
.RI "template<typename T , precision P> GLM_FUNC_DECL \fBdetail::tmat3x3\fP< T, P > \fBglm::diagonal3x3\fP (\fBdetail::tvec3\fP< T, P > const &v)"
.br
.ti -1c
.RI "template<typename T , precision P> GLM_FUNC_DECL \fBdetail::tmat3x4\fP< T, P > \fBglm::diagonal3x4\fP (\fBdetail::tvec3\fP< T, P > const &v)"
.br
.ti -1c
.RI "template<typename T , precision P> GLM_FUNC_DECL \fBdetail::tmat4x2\fP< T, P > \fBglm::diagonal4x2\fP (\fBdetail::tvec2\fP< T, P > const &v)"
.br
.ti -1c
.RI "template<typename T , precision P> GLM_FUNC_DECL \fBdetail::tmat4x3\fP< T, P > \fBglm::diagonal4x3\fP (\fBdetail::tvec3\fP< T, P > const &v)"
.br
.ti -1c
.RI "template<typename T , precision P> GLM_FUNC_DECL \fBdetail::tmat4x4\fP< T, P > \fBglm::diagonal4x4\fP (\fBdetail::tvec4\fP< T, P > const &v)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Build diagonal matrices from vectors\&. 

<\fBglm/gtx/matrix_operation\&.hpp\fP> need to be included to use these functionalities\&. 
.SH "Function Documentation"
.PP 
.SS "template<typename T , precision P> GLM_FUNC_DECL \fBdetail::tmat2x2\fP<T, P> glm::diagonal2x2 (\fBdetail::tvec2\fP< T, P > const & v)"
Build a diagonal matrix\&. From GLM_GTX_matrix_operation extension\&. 
.SS "template<typename T , precision P> GLM_FUNC_DECL \fBdetail::tmat2x3\fP<T, P> glm::diagonal2x3 (\fBdetail::tvec2\fP< T, P > const & v)"
Build a diagonal matrix\&. From GLM_GTX_matrix_operation extension\&. 
.SS "template<typename T , precision P> GLM_FUNC_DECL \fBdetail::tmat2x4\fP<T, P> glm::diagonal2x4 (\fBdetail::tvec2\fP< T, P > const & v)"
Build a diagonal matrix\&. From GLM_GTX_matrix_operation extension\&. 
.SS "template<typename T , precision P> GLM_FUNC_DECL \fBdetail::tmat3x2\fP<T, P> glm::diagonal3x2 (\fBdetail::tvec2\fP< T, P > const & v)"
Build a diagonal matrix\&. From GLM_GTX_matrix_operation extension\&. 
.SS "template<typename T , precision P> GLM_FUNC_DECL \fBdetail::tmat3x3\fP<T, P> glm::diagonal3x3 (\fBdetail::tvec3\fP< T, P > const & v)"
Build a diagonal matrix\&. From GLM_GTX_matrix_operation extension\&. 
.SS "template<typename T , precision P> GLM_FUNC_DECL \fBdetail::tmat3x4\fP<T, P> glm::diagonal3x4 (\fBdetail::tvec3\fP< T, P > const & v)"
Build a diagonal matrix\&. From GLM_GTX_matrix_operation extension\&. 
.SS "template<typename T , precision P> GLM_FUNC_DECL \fBdetail::tmat4x2\fP<T, P> glm::diagonal4x2 (\fBdetail::tvec2\fP< T, P > const & v)"
Build a diagonal matrix\&. From GLM_GTX_matrix_operation extension\&. 
.SS "template<typename T , precision P> GLM_FUNC_DECL \fBdetail::tmat4x3\fP<T, P> glm::diagonal4x3 (\fBdetail::tvec3\fP< T, P > const & v)"
Build a diagonal matrix\&. From GLM_GTX_matrix_operation extension\&. 
.SS "template<typename T , precision P> GLM_FUNC_DECL \fBdetail::tmat4x4\fP<T, P> glm::diagonal4x4 (\fBdetail::tvec4\fP< T, P > const & v)"
Build a diagonal matrix\&. From GLM_GTX_matrix_operation extension\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for IMAC run from the source code\&.
