.TH "gtx_norm" 3 "Tue Dec 18 2018" "IMAC run" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtx_norm \- Various ways to compute vector norms\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename T > GLM_FUNC_DECL T \fBglm::length2\fP (T const &x)"
.br
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL genType::value_type \fBglm::length2\fP (genType const &x)"
.br
.ti -1c
.RI "template<typename T > GLM_FUNC_DECL T \fBglm::distance2\fP (T const &p0, T const &p1)"
.br
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL genType::value_type \fBglm::distance2\fP (genType const &p0, genType const &p1)"
.br
.ti -1c
.RI "template<typename T , precision P> GLM_FUNC_DECL T \fBglm::l1Norm\fP (\fBdetail::tvec3\fP< T, P > const &x, \fBdetail::tvec3\fP< T, P > const &y)"
.br
.ti -1c
.RI "template<typename T , precision P> GLM_FUNC_DECL T \fBglm::l1Norm\fP (\fBdetail::tvec3\fP< T, P > const &v)"
.br
.ti -1c
.RI "template<typename T , precision P> GLM_FUNC_DECL T \fBglm::l2Norm\fP (\fBdetail::tvec3\fP< T, P > const &x, \fBdetail::tvec3\fP< T, P > const &y)"
.br
.ti -1c
.RI "template<typename T , precision P> GLM_FUNC_DECL T \fBglm::l2Norm\fP (\fBdetail::tvec3\fP< T, P > const &x)"
.br
.ti -1c
.RI "template<typename T , precision P> GLM_FUNC_DECL T \fBglm::lxNorm\fP (\fBdetail::tvec3\fP< T, P > const &x, \fBdetail::tvec3\fP< T, P > const &y, unsigned int Depth)"
.br
.ti -1c
.RI "template<typename T , precision P> GLM_FUNC_DECL T \fBglm::lxNorm\fP (\fBdetail::tvec3\fP< T, P > const &x, unsigned int Depth)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Various ways to compute vector norms\&. 

<\fBglm/gtx/norm\&.hpp\fP> need to be included to use these functionalities\&. 
.SH "Function Documentation"
.PP 
.SS "template<typename T > GLM_FUNC_DECL T glm::distance2 (T const & p0, T const & p1)"
Returns the squared distance between p0 and p1, i\&.e\&., length(p0 - p1)\&. From GLM_GTX_norm extension\&. 
.SS "template<typename genType > GLM_FUNC_DECL genType::value_type glm::distance2 (genType const & p0, genType const & p1)"
Returns the squared distance between p0 and p1, i\&.e\&., length(p0 - p1)\&. From GLM_GTX_norm extension\&. 
.SS "template<typename T , precision P> GLM_FUNC_DECL T glm::l1Norm (\fBdetail::tvec3\fP< T, P > const & x, \fBdetail::tvec3\fP< T, P > const & y)"
Returns the L1 norm between x and y\&. From GLM_GTX_norm extension\&. 
.SS "template<typename T , precision P> GLM_FUNC_DECL T glm::l1Norm (\fBdetail::tvec3\fP< T, P > const & v)"
Returns the L1 norm of v\&. From GLM_GTX_norm extension\&. 
.SS "template<typename T , precision P> GLM_FUNC_DECL T glm::l2Norm (\fBdetail::tvec3\fP< T, P > const & x, \fBdetail::tvec3\fP< T, P > const & y)"
Returns the L2 norm between x and y\&. From GLM_GTX_norm extension\&. 
.SS "template<typename T , precision P> GLM_FUNC_DECL T glm::l2Norm (\fBdetail::tvec3\fP< T, P > const & x)"
Returns the L2 norm of v\&. From GLM_GTX_norm extension\&. 
.SS "template<typename T > GLM_FUNC_DECL T glm::length2 (T const & x)"
Returns the squared length of x\&. From GLM_GTX_norm extension\&. 
.SS "template<typename genType > GLM_FUNC_DECL genType::value_type glm::length2 (genType const & x)"
Returns the squared length of x\&. From GLM_GTX_norm extension\&. 
.SS "template<typename T , precision P> GLM_FUNC_DECL T glm::lxNorm (\fBdetail::tvec3\fP< T, P > const & x, \fBdetail::tvec3\fP< T, P > const & y, unsigned int Depth)"
Returns the L norm between x and y\&. From GLM_GTX_norm extension\&. 
.SS "template<typename T , precision P> GLM_FUNC_DECL T glm::lxNorm (\fBdetail::tvec3\fP< T, P > const & x, unsigned int Depth)"
Returns the L norm of v\&. From GLM_GTX_norm extension\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for IMAC run from the source code\&.
