.TH "gtx_matrix_interpolation" 3 "Tue Dec 18 2018" "IMAC run" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtx_matrix_interpolation \- Allows to directly interpolate two exiciting matrices\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename T , precision P> GLM_FUNC_DECL void \fBglm::axisAngle\fP (\fBdetail::tmat4x4\fP< T, P > const &mat, \fBdetail::tvec3\fP< T, P > &\fBaxis\fP, T &\fBangle\fP)"
.br
.ti -1c
.RI "template<typename T , precision P> GLM_FUNC_DECL \fBdetail::tmat4x4\fP< T, P > \fBglm::axisAngleMatrix\fP (\fBdetail::tvec3\fP< T, P > const &\fBaxis\fP, T const \fBangle\fP)"
.br
.ti -1c
.RI "template<typename T , precision P> GLM_FUNC_DECL \fBdetail::tmat4x4\fP< T, P > \fBglm::extractMatrixRotation\fP (\fBdetail::tmat4x4\fP< T, P > const &mat)"
.br
.ti -1c
.RI "template<typename T , precision P> GLM_FUNC_DECL \fBdetail::tmat4x4\fP< T, P > \fBglm::interpolate\fP (\fBdetail::tmat4x4\fP< T, P > const &m1, \fBdetail::tmat4x4\fP< T, P > const &m2, T const delta)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Allows to directly interpolate two exiciting matrices\&. 

<\fBglm/gtx/matrix_interpolation\&.hpp\fP> need to be included to use these functionalities\&. 
.SH "Function Documentation"
.PP 
.SS "template<typename T , precision P> GLM_FUNC_DECL void glm::axisAngle (\fBdetail::tmat4x4\fP< T, P > const & mat, \fBdetail::tvec3\fP< T, P > & axis, T & angle)"
Get the axis and angle of the rotation from a matrix\&. From GLM_GTX_matrix_interpolation extension\&. 
.SS "template<typename T , precision P> GLM_FUNC_DECL \fBdetail::tmat4x4\fP<T, P> glm::axisAngleMatrix (\fBdetail::tvec3\fP< T, P > const & axis, T const angle)"
Build a matrix from axis and angle\&. From GLM_GTX_matrix_interpolation extension\&. 
.SS "template<typename T , precision P> GLM_FUNC_DECL \fBdetail::tmat4x4\fP<T, P> glm::extractMatrixRotation (\fBdetail::tmat4x4\fP< T, P > const & mat)"
Extracts the rotation part of a matrix\&. From GLM_GTX_matrix_interpolation extension\&. 
.SS "template<typename T , precision P> GLM_FUNC_DECL \fBdetail::tmat4x4\fP<T, P> glm::interpolate (\fBdetail::tmat4x4\fP< T, P > const & m1, \fBdetail::tmat4x4\fP< T, P > const & m2, T const delta)"
Build a interpolation of 4 * 4 matrixes\&. From GLM_GTX_matrix_interpolation extension\&. Warning! works only with rotation and/or translation matrixes, scale will generate unexpected results\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for IMAC run from the source code\&.
