.TH "gtx_string_cast" 3 "Tue Dec 18 2018" "IMAC run" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtx_string_cast \- Setup strings for GLM type values\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL std::string \fBglm::to_string\fP (genType const &x)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Setup strings for GLM type values\&. 

<\fBglm/gtx/string_cast\&.hpp\fP> need to be included to use these functionalities\&. This extension is not supported with CUDA 
.SH "Function Documentation"
.PP 
.SS "template<typename genType > GLM_FUNC_DECL std::string glm::to_string (genType const & x)"
Create a string from a GLM type value\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTX_string_cast\fP extension\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for IMAC run from the source code\&.
