.TH "gtx_associated_min_max" 3 "Tue Dec 18 2018" "IMAC run" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtx_associated_min_max \- Min and max functions that return associated values not the compared onces\&. <\fBglm/gtx/associated_min_max\&.hpp\fP> need to be included to use these functionalities\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename genTypeT , typename genTypeU > GLM_FUNC_DECL genTypeU \fBglm::associatedMin\fP (const genTypeT &x, const genTypeU &a, const genTypeT &y, const genTypeU &b)"
.br
.ti -1c
.RI "template<typename genTypeT , typename genTypeU > GLM_FUNC_DECL genTypeU \fBglm::associatedMin\fP (const genTypeT &x, const genTypeU &a, const genTypeT &y, const genTypeU &b, const genTypeT &z, const genTypeU &c)"
.br
.ti -1c
.RI "template<typename genTypeT , typename genTypeU > GLM_FUNC_DECL genTypeU \fBglm::associatedMin\fP (const genTypeT &x, const genTypeU &a, const genTypeT &y, const genTypeU &b, const genTypeT &z, const genTypeU &c, const genTypeT &w, const genTypeU &d)"
.br
.ti -1c
.RI "template<typename genTypeT , typename genTypeU > GLM_FUNC_DECL genTypeU \fBglm::associatedMax\fP (const genTypeT &x, const genTypeU &a, const genTypeT &y, const genTypeU &b)"
.br
.ti -1c
.RI "template<typename genTypeT , typename genTypeU > GLM_FUNC_DECL genTypeU \fBglm::associatedMax\fP (const genTypeT &x, const genTypeU &a, const genTypeT &y, const genTypeU &b, const genTypeT &z, const genTypeU &c)"
.br
.ti -1c
.RI "template<typename genTypeT , typename genTypeU > GLM_FUNC_DECL genTypeU \fBglm::associatedMax\fP (const genTypeT &x, const genTypeU &a, const genTypeT &y, const genTypeU &b, const genTypeT &z, const genTypeU &c, const genTypeT &w, const genTypeU &d)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Min and max functions that return associated values not the compared onces\&. <\fBglm/gtx/associated_min_max\&.hpp\fP> need to be included to use these functionalities\&. 


.SH "Function Documentation"
.PP 
.SS "template<typename genTypeT , typename genTypeU > GLM_FUNC_DECL genTypeU glm::associatedMax (const genTypeT & x, const genTypeU & a, const genTypeT & y, const genTypeU & b)"
Max comparison between 2 variables 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTX_associated_min_max\fP 
.RE
.PP

.SS "template<typename genTypeT , typename genTypeU > GLM_FUNC_DECL genTypeU glm::associatedMax (const genTypeT & x, const genTypeU & a, const genTypeT & y, const genTypeU & b, const genTypeT & z, const genTypeU & c)"
Max comparison between 3 variables 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTX_associated_min_max\fP 
.RE
.PP

.SS "template<typename genTypeT , typename genTypeU > GLM_FUNC_DECL genTypeU glm::associatedMax (const genTypeT & x, const genTypeU & a, const genTypeT & y, const genTypeU & b, const genTypeT & z, const genTypeU & c, const genTypeT & w, const genTypeU & d)"
Max comparison between 4 variables 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTX_associated_min_max\fP 
.RE
.PP

.SS "template<typename genTypeT , typename genTypeU > GLM_FUNC_DECL genTypeU glm::associatedMin (const genTypeT & x, const genTypeU & a, const genTypeT & y, const genTypeU & b)"
Min comparison between 2 variables 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTX_associated_min_max\fP 
.RE
.PP

.SS "template<typename genTypeT , typename genTypeU > GLM_FUNC_DECL genTypeU glm::associatedMin (const genTypeT & x, const genTypeU & a, const genTypeT & y, const genTypeU & b, const genTypeT & z, const genTypeU & c)"
Min comparison between 3 variables 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTX_associated_min_max\fP 
.RE
.PP

.SS "template<typename genTypeT , typename genTypeU > GLM_FUNC_DECL genTypeU glm::associatedMin (const genTypeT & x, const genTypeU & a, const genTypeT & y, const genTypeU & b, const genTypeT & z, const genTypeU & c, const genTypeT & w, const genTypeU & d)"
Min comparison between 4 variables 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTX_associated_min_max\fP 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for IMAC run from the source code\&.
