.TH "gtx_fast_exponential" 3 "Tue Dec 18 2018" "IMAC run" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtx_fast_exponential \- Fast but less accurate implementations of exponential based functions\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL genType \fBglm::fastPow\fP (genType const &x, genType const &y)"
.br
.ti -1c
.RI "template<typename genTypeT , typename genTypeU > GLM_FUNC_DECL genTypeT \fBglm::fastPow\fP (genTypeT const &x, genTypeU const &y)"
.br
.ti -1c
.RI "template<typename T > GLM_FUNC_DECL T \fBglm::fastExp\fP (const T &x)"
.br
.ti -1c
.RI "template<typename T > GLM_FUNC_DECL T \fBglm::fastLog\fP (const T &x)"
.br
.ti -1c
.RI "template<typename T > GLM_FUNC_DECL T \fBglm::fastExp2\fP (const T &x)"
.br
.ti -1c
.RI "template<typename T > GLM_FUNC_DECL T \fBglm::fastLog2\fP (const T &x)"
.br
.ti -1c
.RI "template<typename T > GLM_FUNC_DECL T \fBglm::fastLn\fP (const T &x)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Fast but less accurate implementations of exponential based functions\&. 

<\fBglm/gtx/fast_exponential\&.hpp\fP> need to be included to use these functionalities\&. 
.SH "Function Documentation"
.PP 
.SS "template<typename T > GLM_FUNC_DECL T glm::fastExp (const T & x)"
Faster than the common exp function but less accurate\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTX_fast_exponential\fP 
.RE
.PP

.SS "template<typename T > GLM_FUNC_DECL T glm::fastExp2 (const T & x)"
Faster than the common exp2 function but less accurate\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTX_fast_exponential\fP 
.RE
.PP

.SS "template<typename T > GLM_FUNC_DECL T glm::fastLn (const T & x)"
Faster than the common ln function but less accurate\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTX_fast_exponential\fP 
.RE
.PP

.SS "template<typename T > GLM_FUNC_DECL T glm::fastLog (const T & x)"
Faster than the common log function but less accurate\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTX_fast_exponential\fP 
.RE
.PP

.SS "template<typename T > GLM_FUNC_DECL T glm::fastLog2 (const T & x)"
Faster than the common log2 function but less accurate\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTX_fast_exponential\fP 
.RE
.PP

.SS "template<typename genType > GLM_FUNC_DECL genType glm::fastPow (genType const & x, genType const & y)"
Faster than the common pow function but less accurate\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTX_fast_exponential\fP 
.RE
.PP

.SS "template<typename genTypeT , typename genTypeU > GLM_FUNC_DECL genTypeT glm::fastPow (genTypeT const & x, genTypeU const & y)"
Faster than the common pow function but less accurate\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTX_fast_exponential\fP 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for IMAC run from the source code\&.
