.TH "gtx_perpendicular" 3 "Tue Dec 18 2018" "IMAC run" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtx_perpendicular \- Perpendicular of a vector from other one\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename vecType > GLM_FUNC_DECL vecType \fBglm::perp\fP (vecType const &x, vecType const &Normal)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Perpendicular of a vector from other one\&. 

<\fBglm/gtx/perpendicular\&.hpp\fP> need to be included to use these functionalities\&. 
.SH "Function Documentation"
.PP 
.SS "template<typename vecType > GLM_FUNC_DECL vecType glm::perp (vecType const & x, vecType const & Normal)"
Projects x a perpendicular axis of Normal\&. From GLM_GTX_perpendicular extension\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for IMAC run from the source code\&.
