.TH "gtx_simd_mat4" 3 "Fri Dec 14 2018" "IMAC3_CG_CPP_Game_Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtx_simd_mat4 \- SIMD implementation of mat4 type\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
SIMD implementation of mat4 type\&. 

<\fBglm/gtx/simd_mat4\&.hpp\fP> need to be included to use these functionalities\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for IMAC3_CG_CPP_Game_Project from the source code\&.
