.TH "gtx_vec1" 3 "Tue Dec 18 2018" "IMAC run" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtx_vec1 \- Add vec1, ivec1, uvec1 and bvec1 types\&. <\fBglm/gtx/vec1\&.hpp\fP> need to be included to use these functionalities\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Add vec1, ivec1, uvec1 and bvec1 types\&. <\fBglm/gtx/vec1\&.hpp\fP> need to be included to use these functionalities\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for IMAC run from the source code\&.
