.TH "gtx_log_base" 3 "Fri Dec 14 2018" "IMAC3_CG_CPP_Game_Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtx_log_base \- Logarithm for any base\&. base can be a vector or a scalar\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL genType \fBglm::log\fP (genType const &x, genType const &base)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Logarithm for any base\&. base can be a vector or a scalar\&. 

<\fBglm/gtx/log_base\&.hpp\fP> need to be included to use these functionalities\&. 
.SH "Function Documentation"
.PP 
.SS "template<typename genType > GLM_FUNC_DECL genType glm::log (genType const & x, genType const & base)"
Logarithm for any base\&. From GLM_GTX_log_base\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for IMAC3_CG_CPP_Game_Project from the source code\&.
