.TH "gtx_normal" 3 "Fri Dec 14 2018" "IMAC3_CG_CPP_Game_Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtx_normal \- Compute the normal of a triangle\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename T , precision P> GLM_FUNC_DECL \fBdetail::tvec3\fP< T, P > \fBglm::triangleNormal\fP (\fBdetail::tvec3\fP< T, P > const &p1, \fBdetail::tvec3\fP< T, P > const &p2, \fBdetail::tvec3\fP< T, P > const &p3)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Compute the normal of a triangle\&. 

<\fBglm/gtx/normal\&.hpp\fP> need to be included to use these functionalities\&. 
.SH "Function Documentation"
.PP 
.SS "template<typename T , precision P> GLM_FUNC_DECL \fBdetail::tvec3\fP<T, P> glm::triangleNormal (\fBdetail::tvec3\fP< T, P > const & p1, \fBdetail::tvec3\fP< T, P > const & p2, \fBdetail::tvec3\fP< T, P > const & p3)"
Computes triangle normal from triangle points\&. From GLM_GTX_normal extension\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for IMAC3_CG_CPP_Game_Project from the source code\&.
