.TH "gtx_std_based_type" 3 "Tue Dec 18 2018" "IMAC run" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtx_std_based_type \- Adds vector types based on STL value types\&. <\fBglm/gtx/std_based_type\&.hpp\fP> need to be included to use these functionalities\&.  

.SH SYNOPSIS
.br
.PP
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBdetail::tvec2\fP< std::size_t, defaultp > \fBglm::size2\fP"
.br
.ti -1c
.RI "typedef \fBdetail::tvec3\fP< std::size_t, defaultp > \fBglm::size3\fP"
.br
.ti -1c
.RI "typedef \fBdetail::tvec4\fP< std::size_t, defaultp > \fBglm::size4\fP"
.br
.ti -1c
.RI "typedef \fBdetail::tvec2\fP< std::size_t, defaultp > \fBglm::size2_t\fP"
.br
.ti -1c
.RI "typedef \fBdetail::tvec3\fP< std::size_t, defaultp > \fBglm::size3_t\fP"
.br
.ti -1c
.RI "typedef \fBdetail::tvec4\fP< std::size_t, defaultp > \fBglm::size4_t\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Adds vector types based on STL value types\&. <\fBglm/gtx/std_based_type\&.hpp\fP> need to be included to use these functionalities\&. 


.SH "Typedef Documentation"
.PP 
.SS "typedef \fBdetail::tvec2\fP<std::size_t, defaultp> \fBglm::size2\fP"
Vector type based of two std::size_t components\&. 
.PP
\fBSee also:\fP
.RS 4
GLM_GTX_std_based_type 
.RE
.PP

.SS "typedef \fBdetail::tvec2\fP<std::size_t, defaultp> \fBglm::size2_t\fP"
Vector type based of two std::size_t components\&. 
.PP
\fBSee also:\fP
.RS 4
GLM_GTX_std_based_type 
.RE
.PP

.SS "typedef \fBdetail::tvec3\fP<std::size_t, defaultp> \fBglm::size3\fP"
Vector type based of three std::size_t components\&. 
.PP
\fBSee also:\fP
.RS 4
GLM_GTX_std_based_type 
.RE
.PP

.SS "typedef \fBdetail::tvec3\fP<std::size_t, defaultp> \fBglm::size3_t\fP"
Vector type based of three std::size_t components\&. 
.PP
\fBSee also:\fP
.RS 4
GLM_GTX_std_based_type 
.RE
.PP

.SS "typedef \fBdetail::tvec4\fP<std::size_t, defaultp> \fBglm::size4\fP"
Vector type based of four std::size_t components\&. 
.PP
\fBSee also:\fP
.RS 4
GLM_GTX_std_based_type 
.RE
.PP

.SS "typedef \fBdetail::tvec4\fP<std::size_t, defaultp> \fBglm::size4_t\fP"
Vector type based of four std::size_t components\&. 
.PP
\fBSee also:\fP
.RS 4
GLM_GTX_std_based_type 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for IMAC run from the source code\&.
