.TH "gtx_rotate_vector" 3 "Fri Dec 14 2018" "IMAC3_CG_CPP_Game_Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtx_rotate_vector \- Function to directly rotate a vector\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename T , precision P> GLM_FUNC_DECL \fBdetail::tvec2\fP< T, P > \fBglm::rotate\fP (\fBdetail::tvec2\fP< T, P > const &v, T const &\fBangle\fP)"
.br
.ti -1c
.RI "template<typename T , precision P> GLM_FUNC_DECL \fBdetail::tvec3\fP< T, P > \fBglm::rotate\fP (\fBdetail::tvec3\fP< T, P > const &v, T const &\fBangle\fP, \fBdetail::tvec3\fP< T, P > const &normal)"
.br
.ti -1c
.RI "template<typename T , precision P> GLM_FUNC_DECL \fBdetail::tvec4\fP< T, P > \fBglm::rotate\fP (\fBdetail::tvec4\fP< T, P > const &v, T const &\fBangle\fP, \fBdetail::tvec3\fP< T, P > const &normal)"
.br
.ti -1c
.RI "template<typename T , precision P> GLM_FUNC_DECL \fBdetail::tvec3\fP< T, P > \fBglm::rotateX\fP (\fBdetail::tvec3\fP< T, P > const &v, T const &\fBangle\fP)"
.br
.ti -1c
.RI "template<typename T , precision P> GLM_FUNC_DECL \fBdetail::tvec3\fP< T, P > \fBglm::rotateY\fP (\fBdetail::tvec3\fP< T, P > const &v, T const &\fBangle\fP)"
.br
.ti -1c
.RI "template<typename T , precision P> GLM_FUNC_DECL \fBdetail::tvec3\fP< T, P > \fBglm::rotateZ\fP (\fBdetail::tvec3\fP< T, P > const &v, T const &\fBangle\fP)"
.br
.ti -1c
.RI "template<typename T , precision P> GLM_FUNC_DECL \fBdetail::tvec4\fP< T, P > \fBglm::rotateX\fP (\fBdetail::tvec4\fP< T, P > const &v, T const &\fBangle\fP)"
.br
.ti -1c
.RI "template<typename T , precision P> GLM_FUNC_DECL \fBdetail::tvec4\fP< T, P > \fBglm::rotateY\fP (\fBdetail::tvec4\fP< T, P > const &v, T const &\fBangle\fP)"
.br
.ti -1c
.RI "template<typename T , precision P> GLM_FUNC_DECL \fBdetail::tvec4\fP< T, P > \fBglm::rotateZ\fP (\fBdetail::tvec4\fP< T, P > const &v, T const &\fBangle\fP)"
.br
.ti -1c
.RI "template<typename T , precision P> GLM_FUNC_DECL \fBdetail::tmat4x4\fP< T, P > \fBglm::orientation\fP (\fBdetail::tvec3\fP< T, P > const &Normal, \fBdetail::tvec3\fP< T, P > const &Up)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Function to directly rotate a vector\&. 

<\fBglm/gtx/rotate_vector\&.hpp\fP> need to be included to use these functionalities\&. 
.SH "Function Documentation"
.PP 
.SS "template<typename T , precision P> GLM_FUNC_DECL \fBdetail::tmat4x4\fP<T, P> glm::orientation (\fBdetail::tvec3\fP< T, P > const & Normal, \fBdetail::tvec3\fP< T, P > const & Up)"
Build a rotation matrix from a normal and a up vector\&. From GLM_GTX_rotate_vector extension\&. 
.SS "template<typename T , precision P> GLM_FUNC_DECL \fBdetail::tvec2\fP<T, P> glm::rotate (\fBdetail::tvec2\fP< T, P > const & v, T const & angle)"
Rotate a two dimensional vector\&. From GLM_GTX_rotate_vector extension\&. 
.SS "template<typename T , precision P> GLM_FUNC_DECL \fBdetail::tvec3\fP<T, P> glm::rotate (\fBdetail::tvec3\fP< T, P > const & v, T const & angle, \fBdetail::tvec3\fP< T, P > const & normal)"
Rotate a three dimensional vector around an axis\&. From GLM_GTX_rotate_vector extension\&. 
.SS "template<typename T , precision P> GLM_FUNC_DECL \fBdetail::tvec4\fP<T, P> glm::rotate (\fBdetail::tvec4\fP< T, P > const & v, T const & angle, \fBdetail::tvec3\fP< T, P > const & normal)"
Rotate a four dimensional vector around an axis\&. From GLM_GTX_rotate_vector extension\&. 
.SS "template<typename T , precision P> GLM_FUNC_DECL \fBdetail::tvec3\fP<T, P> glm::rotateX (\fBdetail::tvec3\fP< T, P > const & v, T const & angle)"
Rotate a three dimensional vector around the X axis\&. From GLM_GTX_rotate_vector extension\&. 
.SS "template<typename T , precision P> GLM_FUNC_DECL \fBdetail::tvec4\fP<T, P> glm::rotateX (\fBdetail::tvec4\fP< T, P > const & v, T const & angle)"
Rotate a four dimentionnals vector around the X axis\&. From GLM_GTX_rotate_vector extension\&. 
.SS "template<typename T , precision P> GLM_FUNC_DECL \fBdetail::tvec3\fP<T, P> glm::rotateY (\fBdetail::tvec3\fP< T, P > const & v, T const & angle)"
Rotate a three dimensional vector around the Y axis\&. From GLM_GTX_rotate_vector extension\&. 
.SS "template<typename T , precision P> GLM_FUNC_DECL \fBdetail::tvec4\fP<T, P> glm::rotateY (\fBdetail::tvec4\fP< T, P > const & v, T const & angle)"
Rotate a four dimensional vector around the X axis\&. From GLM_GTX_rotate_vector extension\&. 
.SS "template<typename T , precision P> GLM_FUNC_DECL \fBdetail::tvec3\fP<T, P> glm::rotateZ (\fBdetail::tvec3\fP< T, P > const & v, T const & angle)"
Rotate a three dimensional vector around the Z axis\&. From GLM_GTX_rotate_vector extension\&. 
.SS "template<typename T , precision P> GLM_FUNC_DECL \fBdetail::tvec4\fP<T, P> glm::rotateZ (\fBdetail::tvec4\fP< T, P > const & v, T const & angle)"
Rotate a four dimensional vector around the X axis\&. From GLM_GTX_rotate_vector extension\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for IMAC3_CG_CPP_Game_Project from the source code\&.
