.TH "gtx_mixed_product" 3 "Fri Dec 14 2018" "IMAC3_CG_CPP_Game_Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtx_mixed_product \- Mixed product of 3 vectors\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename T , precision P> GLM_FUNC_DECL T \fBglm::mixedProduct\fP (\fBdetail::tvec3\fP< T, P > const &v1, \fBdetail::tvec3\fP< T, P > const &v2, \fBdetail::tvec3\fP< T, P > const &v3)"
.br
.RI "Mixed product of 3 vectors (from GLM_GTX_mixed_product extension) "
.in -1c
.SH "Detailed Description"
.PP 
Mixed product of 3 vectors\&. 

<\fBglm/gtx/mixed_product\&.hpp\fP> need to be included to use these functionalities\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for IMAC3_CG_CPP_Game_Project from the source code\&.
