.TH "gtx_transform" 3 "Tue Dec 18 2018" "IMAC run" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtx_transform \- Add transformation matrices\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename T , precision P> GLM_FUNC_DECL \fBdetail::tmat4x4\fP< T, P > \fBglm::translate\fP (\fBdetail::tvec3\fP< T, P > const &v)"
.br
.ti -1c
.RI "template<typename T , precision P> GLM_FUNC_DECL \fBdetail::tmat4x4\fP< T, P > \fBglm::rotate\fP (T \fBangle\fP, \fBdetail::tvec3\fP< T, P > const &v)"
.br
.ti -1c
.RI "template<typename T , precision P> GLM_FUNC_DECL \fBdetail::tmat4x4\fP< T, P > \fBglm::scale\fP (\fBdetail::tvec3\fP< T, P > const &v)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Add transformation matrices\&. 

<\fBglm/gtx/transform\&.hpp\fP> need to be included to use these functionalities\&. 
.SH "Function Documentation"
.PP 
.SS "template<typename T , precision P> GLM_FUNC_DECL \fBdetail::tmat4x4\fP<T, P> glm::rotate (T angle, \fBdetail::tvec3\fP< T, P > const & v)"
Builds a rotation 4 * 4 matrix created from an axis of 3 scalars and an angle expressed in degrees\&.
.IP "\(bu" 2
From \fBGLM_GTX_transform \fP extension
.IP "\(bu" 2
See also: \fBGLM_GTC_matrix_transform \fP 
.PP

.SS "template<typename T , precision P> GLM_FUNC_DECL \fBdetail::tmat4x4\fP<T, P> glm::scale (\fBdetail::tvec3\fP< T, P > const & v)"
Transforms a matrix with a scale 4 * 4 matrix created from a vector of 3 components\&.
.IP "\(bu" 2
From \fBGLM_GTX_transform \fP extension
.IP "\(bu" 2
See also: \fBGLM_GTC_matrix_transform \fP 
.PP

.SS "template<typename T , precision P> GLM_FUNC_DECL \fBdetail::tmat4x4\fP<T, P> glm::translate (\fBdetail::tvec3\fP< T, P > const & v)"
Transforms a matrix with a translation 4 * 4 matrix created from 3 scalars\&.
.IP "\(bu" 2
From \fBGLM_GTX_transform \fP extension
.IP "\(bu" 2
See also: \fBGLM_GTC_matrix_transform \fP 
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for IMAC run from the source code\&.
