.TH "gtx_multiple" 3 "Tue Dec 18 2018" "IMAC run" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtx_multiple \- Find the closest number of a number multiple of other number\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL genType \fBglm::higherMultiple\fP (genType const &Source, genType const &Multiple)"
.br
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL genType \fBglm::lowerMultiple\fP (genType const &Source, genType const &Multiple)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Find the closest number of a number multiple of other number\&. 

<\fBglm/gtx/multiple\&.hpp\fP> need to be included to use these functionalities\&. 
.SH "Function Documentation"
.PP 
.SS "template<typename genType > GLM_FUNC_DECL genType glm::higherMultiple (genType const & Source, genType const & Multiple)"
Higher multiple number of Source\&.
.PP
\fBTemplate Parameters:\fP
.RS 4
\fIgenType\fP Floating-point or integer scalar or vector types\&. 
.RE
.PP
\fBParameters:\fP
.RS 4
\fISource\fP 
.br
\fIMultiple\fP Must be a null or positive value
.RE
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTX_multiple\fP 
.RE
.PP

.SS "template<typename genType > GLM_FUNC_DECL genType glm::lowerMultiple (genType const & Source, genType const & Multiple)"
Lower multiple number of Source\&.
.PP
\fBTemplate Parameters:\fP
.RS 4
\fIgenType\fP Floating-point or integer scalar or vector types\&. 
.RE
.PP
\fBParameters:\fP
.RS 4
\fISource\fP 
.br
\fIMultiple\fP Must be a null or positive value
.RE
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTX_multiple\fP 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for IMAC run from the source code\&.
