.TH "gtx_inertia" 3 "Fri Dec 14 2018" "IMAC3_CG_CPP_Game_Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtx_inertia \- Create inertia matrices\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Create inertia matrices\&. 

<\fBglm/gtx/inertia\&.hpp\fP> need to be included to use these functionalities\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for IMAC3_CG_CPP_Game_Project from the source code\&.
