.TH "gtx_closest_point" 3 "Tue Dec 18 2018" "IMAC run" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtx_closest_point \- Find the point on a straight line which is the closet of a point\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename T , precision P> GLM_FUNC_DECL \fBdetail::tvec3\fP< T, P > \fBglm::closestPointOnLine\fP (\fBdetail::tvec3\fP< T, P > const &point, \fBdetail::tvec3\fP< T, P > const &a, \fBdetail::tvec3\fP< T, P > const &b)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Find the point on a straight line which is the closet of a point\&. 

<\fBglm/gtx/closest_point\&.hpp\fP> need to be included to use these functionalities\&. 
.SH "Function Documentation"
.PP 
.SS "template<typename T , precision P> GLM_FUNC_DECL \fBdetail::tvec3\fP<T, P> glm::closestPointOnLine (\fBdetail::tvec3\fP< T, P > const & point, \fBdetail::tvec3\fP< T, P > const & a, \fBdetail::tvec3\fP< T, P > const & b)"
Find the point on a straight line which is the closet of a point\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTX_closest_point\fP 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for IMAC run from the source code\&.
