.TH "gtx_projection" 3 "Fri Dec 14 2018" "IMAC3_CG_CPP_Game_Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtx_projection \- Projection of a vector to other one\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename vecType > GLM_FUNC_DECL vecType \fBglm::proj\fP (vecType const &x, vecType const &Normal)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Projection of a vector to other one\&. 

<\fBglm/gtx/projection\&.hpp\fP> need to be included to use these functionalities\&. 
.SH "Function Documentation"
.PP 
.SS "template<typename vecType > GLM_FUNC_DECL vecType glm::proj (vecType const & x, vecType const & Normal)"
Projects x on Normal\&. From GLM_GTX_projection extension\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for IMAC3_CG_CPP_Game_Project from the source code\&.
