.TH "gtx_io" 3 "Tue Dec 18 2018" "IMAC run" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtx_io \- std::[w]ostream support for glm types  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
std::[w]ostream support for glm types 

std::[w]ostream support for glm types + precision/width/etc\&. manipulators based on howard hinnant's std::chrono io proposal [http://home.roadrunner.com/~hinnant/bloomington/chrono_io.html]
.PP
<\fBglm/gtx/io\&.hpp\fP> needs to be included to use these functionalities\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for IMAC run from the source code\&.
