.TH "gtx_simd_vec4" 3 "Tue Dec 18 2018" "IMAC run" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtx_simd_vec4 \- SIMD implementation of quat type\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
SIMD implementation of quat type\&. 

SIMD implementation of vec4 type\&.
.PP
<\fBglm/gtx/simd_quat\&.hpp\fP> need to be included to use these functionalities\&.
.PP
<\fBglm/gtx/simd_vec4\&.hpp\fP> need to be included to use these functionalities\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for IMAC run from the source code\&.
