.TH "gtx_polar_coordinates" 3 "Tue Dec 18 2018" "IMAC run" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtx_polar_coordinates \- Conversion from Euclidean space to polar space and revert\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename T , precision P> GLM_FUNC_DECL \fBdetail::tvec3\fP< T, P > \fBglm::polar\fP (\fBdetail::tvec3\fP< T, P > const &\fBeuclidean\fP)"
.br
.ti -1c
.RI "template<typename T , precision P> GLM_FUNC_DECL \fBdetail::tvec3\fP< T, P > \fBglm::euclidean\fP (\fBdetail::tvec2\fP< T, P > const &\fBpolar\fP)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Conversion from Euclidean space to polar space and revert\&. 

<\fBglm/gtx/polar_coordinates\&.hpp\fP> need to be included to use these functionalities\&. 
.SH "Function Documentation"
.PP 
.SS "template<typename T , precision P> GLM_FUNC_DECL \fBdetail::tvec3\fP<T, P> glm::euclidean (\fBdetail::tvec2\fP< T, P > const & polar)"
Convert Polar to Euclidean coordinates\&.
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTX_polar_coordinates\fP 
.RE
.PP

.SS "template<typename T , precision P> GLM_FUNC_DECL \fBdetail::tvec3\fP<T, P> glm::polar (\fBdetail::tvec3\fP< T, P > const & euclidean)"
Convert Euclidean to Polar coordinates, x is the xz distance, y, the latitude and z the longitude\&.
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTX_polar_coordinates\fP 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for IMAC run from the source code\&.
