.TH "gtx_color_space_YCoCg" 3 "Fri Dec 14 2018" "IMAC3_CG_CPP_Game_Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtx_color_space_YCoCg \- RGB to YCoCg conversions and operations\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename T , precision P> GLM_FUNC_DECL \fBdetail::tvec3\fP< T, P > \fBglm::rgb2YCoCg\fP (\fBdetail::tvec3\fP< T, P > const &\fBrgbColor\fP)"
.br
.ti -1c
.RI "template<typename T , precision P> GLM_FUNC_DECL \fBdetail::tvec3\fP< T, P > \fBglm::YCoCg2rgb\fP (\fBdetail::tvec3\fP< T, P > const &YCoCgColor)"
.br
.ti -1c
.RI "template<typename T , precision P> GLM_FUNC_DECL \fBdetail::tvec3\fP< T, P > \fBglm::rgb2YCoCgR\fP (\fBdetail::tvec3\fP< T, P > const &\fBrgbColor\fP)"
.br
.ti -1c
.RI "template<typename T , precision P> GLM_FUNC_DECL \fBdetail::tvec3\fP< T, P > \fBglm::YCoCgR2rgb\fP (\fBdetail::tvec3\fP< T, P > const &YCoCgColor)"
.br
.in -1c
.SH "Detailed Description"
.PP 
RGB to YCoCg conversions and operations\&. 

<\fBglm/gtx/color_space_YCoCg\&.hpp\fP> need to be included to use these functionalities\&. 
.SH "Function Documentation"
.PP 
.SS "template<typename T , precision P> GLM_FUNC_DECL \fBdetail::tvec3\fP<T, P> glm::rgb2YCoCg (\fBdetail::tvec3\fP< T, P > const & rgbColor)"
Convert a color from RGB color space to YCoCg color space\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTX_color_space_YCoCg\fP 
.RE
.PP

.SS "template<typename T , precision P> GLM_FUNC_DECL \fBdetail::tvec3\fP<T, P> glm::rgb2YCoCgR (\fBdetail::tvec3\fP< T, P > const & rgbColor)"
Convert a color from RGB color space to YCoCgR color space\&. 
.PP
\fBSee also:\fP
.RS 4
'YCoCg-R: A Color Space with RGB Reversibility and Low Dynamic Range' 
.PP
\fBGLM_GTX_color_space_YCoCg\fP 
.RE
.PP

.SS "template<typename T , precision P> GLM_FUNC_DECL \fBdetail::tvec3\fP<T, P> glm::YCoCg2rgb (\fBdetail::tvec3\fP< T, P > const & YCoCgColor)"
Convert a color from YCoCg color space to RGB color space\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTX_color_space_YCoCg\fP 
.RE
.PP

.SS "template<typename T , precision P> GLM_FUNC_DECL \fBdetail::tvec3\fP<T, P> glm::YCoCgR2rgb (\fBdetail::tvec3\fP< T, P > const & YCoCgColor)"
Convert a color from YCoCgR color space to RGB color space\&. 
.PP
\fBSee also:\fP
.RS 4
'YCoCg-R: A Color Space with RGB Reversibility and Low Dynamic Range' 
.PP
\fBGLM_GTX_color_space_YCoCg\fP 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for IMAC3_CG_CPP_Game_Project from the source code\&.
