.TH "gtx_matrix_cross_product" 3 "Fri Dec 14 2018" "IMAC3_CG_CPP_Game_Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtx_matrix_cross_product \- Build cross product matrices\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename T , precision P> GLM_FUNC_DECL \fBdetail::tmat3x3\fP< T, P > \fBglm::matrixCross3\fP (\fBdetail::tvec3\fP< T, P > const &x)"
.br
.ti -1c
.RI "template<typename T , precision P> GLM_FUNC_DECL \fBdetail::tmat4x4\fP< T, P > \fBglm::matrixCross4\fP (\fBdetail::tvec3\fP< T, P > const &x)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Build cross product matrices\&. 

<\fBglm/gtx/matrix_cross_product\&.hpp\fP> need to be included to use these functionalities\&. 
.SH "Function Documentation"
.PP 
.SS "template<typename T , precision P> GLM_FUNC_DECL \fBdetail::tmat3x3\fP<T, P> glm::matrixCross3 (\fBdetail::tvec3\fP< T, P > const & x)"
Build a cross product matrix\&. From GLM_GTX_matrix_cross_product extension\&. 
.SS "template<typename T , precision P> GLM_FUNC_DECL \fBdetail::tmat4x4\fP<T, P> glm::matrixCross4 (\fBdetail::tvec3\fP< T, P > const & x)"
Build a cross product matrix\&. From GLM_GTX_matrix_cross_product extension\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for IMAC3_CG_CPP_Game_Project from the source code\&.
