.TH "gtx_fast_square_root" 3 "Tue Dec 18 2018" "IMAC run" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtx_fast_square_root \- Fast but less accurate implementations of square root based functions\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL genType \fBglm::fastSqrt\fP (genType const &x)"
.br
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL genType \fBglm::fastInverseSqrt\fP (genType const &x)"
.br
.ti -1c
.RI "template<typename T , precision P, template< typename, precision > class vecType> GLM_FUNC_DECL vecType< T, P > \fBglm::fastInverseSqrt\fP (vecType< T, P > const &x)"
.br
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL genType::value_type \fBglm::fastLength\fP (genType const &x)"
.br
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL genType::value_type \fBglm::fastDistance\fP (genType const &x, genType const &y)"
.br
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL genType \fBglm::fastNormalize\fP (genType const &x)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Fast but less accurate implementations of square root based functions\&. 


.IP "\(bu" 2
Sqrt optimisation based on Newton's method, www\&.gamedev\&.net/community/forums/topic\&.asp?topic id=139956
.PP
.PP
<\fBglm/gtx/fast_square_root\&.hpp\fP> need to be included to use these functionalities\&. 
.SH "Function Documentation"
.PP 
.SS "template<typename genType > GLM_FUNC_DECL genType::value_type glm::fastDistance (genType const & x, genType const & y)"
Faster than the common distance function but less accurate\&. From GLM_GTX_fast_square_root extension\&. 
.SS "template<typename genType > GLM_FUNC_DECL genType glm::fastInverseSqrt (genType const & x)"
Faster than the common inversesqrt function but less accurate\&. From GLM_GTX_fast_square_root extension\&. 
.SS "template<typename T , precision P, template< typename, precision > class vecType> GLM_FUNC_DECL vecType<T, P> glm::fastInverseSqrt (vecType< T, P > const & x)"
Faster than the common inversesqrt function but less accurate\&. From GLM_GTX_fast_square_root extension\&. 
.SS "template<typename genType > GLM_FUNC_DECL genType::value_type glm::fastLength (genType const & x)"
Faster than the common length function but less accurate\&. From GLM_GTX_fast_square_root extension\&. 
.SS "template<typename genType > GLM_FUNC_DECL genType glm::fastNormalize (genType const & x)"
Faster than the common normalize function but less accurate\&. From GLM_GTX_fast_square_root extension\&. 
.SS "template<typename genType > GLM_FUNC_DECL genType glm::fastSqrt (genType const & x)"
Faster than the common sqrt function but less accurate\&. From GLM_GTX_fast_square_root extension\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for IMAC run from the source code\&.
