.TH "gtx_orthonormalize" 3 "Tue Dec 18 2018" "IMAC run" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtx_orthonormalize \- Orthonormalize matrices\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename T , precision P> GLM_FUNC_DECL \fBdetail::tmat3x3\fP< T, P > \fBglm::orthonormalize\fP (const \fBdetail::tmat3x3\fP< T, P > &m)"
.br
.ti -1c
.RI "template<typename T , precision P> GLM_FUNC_DECL \fBdetail::tvec3\fP< T, P > \fBglm::orthonormalize\fP (const \fBdetail::tvec3\fP< T, P > &x, const \fBdetail::tvec3\fP< T, P > &y)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Orthonormalize matrices\&. 

<\fBglm/gtx/orthonormalize\&.hpp\fP> need to be included to use these functionalities\&. 
.SH "Function Documentation"
.PP 
.SS "template<typename T , precision P> GLM_FUNC_DECL \fBdetail::tmat3x3\fP<T, P> glm::orthonormalize (const \fBdetail::tmat3x3\fP< T, P > & m)"
Returns the orthonormalized matrix of m\&. From GLM_GTX_orthonormalize extension\&. 
.SS "template<typename T , precision P> GLM_FUNC_DECL \fBdetail::tvec3\fP<T, P> glm::orthonormalize (const \fBdetail::tvec3\fP< T, P > & x, const \fBdetail::tvec3\fP< T, P > & y)"
Orthonormalizes x according y\&. From GLM_GTX_orthonormalize extension\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for IMAC run from the source code\&.
