.TH "ieee_double_shape_type" 3 "Fri Dec 14 2018" "IMAC3_CG_CPP_Game_Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ieee_double_shape_type
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBvalue\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   glm::detail::int32 \fBlsw\fP"
.br
.ti -1c
.RI "   glm::detail::int32 \fBmsw\fP"
.br
.ti -1c
.RI "} \fBparts\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for IMAC3_CG_CPP_Game_Project from the source code\&.
