.TH "KeyboardEventObserver" 3 "Fri Dec 14 2018" "IMAC3_CG_CPP_Game_Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KeyboardEventObserver
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <EventObservers\&.hpp>\fP
.PP
Inherited by \fBGameController\fP\fC [private]\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBkeyRealeaseHandler\fP (unsigned char keycode)"
.br
.ti -1c
.RI "virtual void \fBkeyDownHandler\fP (unsigned char keycode)"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBKeyboardEventObserver\fP Interface
.PP
Classes implementing this interface can subscribe to key events in EventManager 

.SH "Author"
.PP 
Generated automatically by Doxygen for IMAC3_CG_CPP_Game_Project from the source code\&.
