.TH "light" 3 "Fri Dec 14 2018" "IMAC3_CG_CPP_Game_Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
light
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBglm::vec4\fP \fBambient\fP"
.br
.ti -1c
.RI "\fBglm::vec4\fP \fBdiffuse\fP"
.br
.ti -1c
.RI "\fBglm::vec4\fP \fBspecular\fP"
.br
.ti -1c
.RI "\fBglm::vec4\fP \fBposition\fP"
.br
.ti -1c
.RI "\fBglm::vec4\fP \fBhalfVector\fP"
.br
.ti -1c
.RI "\fBglm::vec3\fP \fBspotDirection\fP"
.br
.ti -1c
.RI "float \fBspotExponent\fP"
.br
.ti -1c
.RI "float \fBspotCutoff\fP"
.br
.ti -1c
.RI "float \fBspotCosCutoff\fP"
.br
.ti -1c
.RI "float \fBconstantAttenuation\fP"
.br
.ti -1c
.RI "float \fBlinearAttenuation\fP"
.br
.ti -1c
.RI "float \fBquadraticAttenuation\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for IMAC3_CG_CPP_Game_Project from the source code\&.
