.TH "material" 3 "Tue Dec 18 2018" "IMAC run" \" -*- nroff -*-
.ad l
.nh
.SH NAME
material
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBglm::vec4\fP \fBemission\fP"
.br
.ti -1c
.RI "\fBglm::vec4\fP \fBambient\fP"
.br
.ti -1c
.RI "\fBglm::vec4\fP \fBdiffuse\fP"
.br
.ti -1c
.RI "\fBglm::vec4\fP \fBspecular\fP"
.br
.ti -1c
.RI "float \fBshininess\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for IMAC run from the source code\&.
