.TH "md__r_e_a_d_m_e" 3 "Fri Dec 14 2018" "IMAC3_CG_CPP_Game_Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__r_e_a_d_m_e# Temple-run-like-game 
 \- \fBC++/Computer Graphics Project - IMAC 2 - 2018\fP
.PP
.SS "About"
.PP
\&.\&. TODO
.PP
.SS "Requirements"
.PP
.IP "\(bu" 2
Linux or Mac OS\&.
.IP "\(bu" 2
OpenGL 3\&.+, GLEW 2\&.+, SDL 2\&.+, SDL_Image 2+
.IP "\(bu" 2
Doxygen (soon)
.PP
.PP
.SS "Setup environnement"
.PP
.IP "1." 4
install dependencies (sdl2, image, glew\&.\&.\&. )
.IP "2." 4
make ( -j + number of CPU cors you have - 1) 
.PP

