.TH "MouseEventObserver" 3 "Fri Dec 14 2018" "IMAC3_CG_CPP_Game_Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MouseEventObserver
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <EventObservers\&.hpp>\fP
.PP
Inherited by \fBGameController\fP\fC [private]\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBmouseReleaseHandler\fP (unsigned char button)"
.br
.ti -1c
.RI "virtual void \fBmouseDownHandler\fP (unsigned char button)"
.br
.ti -1c
.RI "virtual void \fBmouseMoveHandler\fP (float relativeXMovement, float relativeYMovement)"
.br
.ti -1c
.RI "virtual void \fBmouseWheelHandler\fP (float deltaX, float deltaY)"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBMouseEventObserver\fP Interface
.PP
Classes implementing this interface can subscribe to mouse events in EventManager 

.SH "Author"
.PP 
Generated automatically by Doxygen for IMAC3_CG_CPP_Game_Project from the source code\&.
