.TH "todo" 3 "Fri Dec 14 2018" "IMAC3_CG_CPP_Game_Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
todoTodo List 
 \- 
.IP "\fBMember \fBglm::bitCount\fP (genIUType< T > const &Value)\fP" 1c
Clarify the declaration to specify that scalars are suported\&.  
.IP "\fBMember \fBglm::epsilon\fP ()\fP" 1c
Implement epsilon for half-precision floating point type\&.  
.IP "\fBMember \fBglm::findLSB\fP (genIUType< T > const &Value)\fP" 1c
Clarify the declaration to specify that scalars are suported\&.  
.IP "\fBMember \fBglm::findMSB\fP (genIUType< T > const &Value)\fP" 1c
Clarify the declaration to specify that scalars are suported\&.  
.IP "\fBMember \fBglm::orientedAngle\fP (detail::tvec2< T, P > const &x, detail::tvec2< T, P > const &y)\fP" 1c
epsilon is hard coded to 0\&.01  
.IP "\fBMember \fBglm::outerProduct\fP (vecTypeA< T, P > const &c, vecTypeB< T, P > const &r)\fP" 1c
Clarify the declaration to specify that matType doesn't have to be provided when used\&. 
.PP

